export type AlgorithmKind = "Generator" | "Solver";

export interface AlgorithmDoc {
  id: string;
  name: string;
  kind: AlgorithmKind;
  summary: string;
  howItWorks: string[];
  timeComplexity: string;
  spaceComplexity: string;
  pros: string[];
  cons: string[];
  bestFor: string;
  interestingFact: string;
}

export const ALGORITHM_DOCS: AlgorithmDoc[] = [
  {
    id: "dfs-backtracker",
    name: "Recursive Backtracker (DFS)",
    kind: "Generator",
    summary: "Grows a maze by walking deeply until stuck, then backtracks.",
    howItWorks: [
      "Start at one cell, mark it visited, and push it on a stack.",
      "Move to a random unvisited neighbor and carve the wall.",
      "If no unvisited neighbors remain, pop and continue from the previous cell.",
      "Stop when the stack becomes empty.",
    ],
    timeComplexity: "O(V)",
    spaceComplexity: "O(V)",
    pros: ["Fast", "Simple", "Produces long winding corridors"],
    cons: ["Can create low branching", "Less uniform than Wilson/Aldous-Broder"],
    bestFor: "Fast visual generation with dramatic backtracking behavior.",
    interestingFact:
      "This is one of the most common textbook maze generators because it is easy to animate step-by-step.",
  },
  {
    id: "prim",
    name: "Randomized Prim",
    kind: "Generator",
    summary: "Expands a frontier set by attaching random frontier cells.",
    howItWorks: [
      "Start from one cell and mark adjacent cells as frontier.",
      "Pick a random frontier cell.",
      "Connect it to one random visited neighbor.",
      "Mark its unvisited neighbors as new frontier.",
    ],
    timeComplexity: "O(V)",
    spaceComplexity: "O(V)",
    pros: ["Good branching", "Natural wavefront animation"],
    cons: ["Needs frontier bookkeeping", "Can look noisy at high randomness"],
    bestFor: "Balanced mazes with lots of local choices.",
    interestingFact:
      "It is inspired by Prim's minimum spanning tree method, but with randomized edge selection.",
  },
  {
    id: "prim-loopy",
    name: "Prim (Loopy)",
    kind: "Generator",
    summary:
      "Prim-style frontier growth that intentionally opens extra visited-neighbor links.",
    howItWorks: [
      "Pick random frontier cells and connect each to one visited parent, like standard Prim.",
      "After parent carve, sample additional visited neighbors.",
      "Open some extra links using a configurable loop-density probability.",
      "Continue until all cells are visited.",
    ],
    timeComplexity: "O(V + E) expected",
    spaceComplexity: "O(V)",
    pros: ["Simple loop control", "Keeps Prim wavefront visual style"],
    cons: ["Higher loop density can reduce dead-end challenge", "Not a perfect maze"],
    bestFor: "Tunable loop-heavy mazes with local alternate routes.",
    interestingFact:
      "This variant keeps Prim's growth order but relaxes the acyclic constraint after each frontier attachment.",
  },
  {
    id: "prim-frontier-edges",
    name: "Prim (Frontier Edges)",
    kind: "Generator",
    summary: "Prim-style generation using explicit frontier edge sampling.",
    howItWorks: [
      "Start from one visited root cell.",
      "Push all edges from visited cells to unvisited neighbors into a frontier list.",
      "Pick a random frontier edge; if it connects to an unvisited cell, carve it.",
      "Add new frontier edges from the newly visited cell and repeat.",
    ],
    timeComplexity: "O(E) expected",
    spaceComplexity: "O(E)",
    pros: ["Classic Prim interpretation", "Good branching and texture"],
    cons: ["Frontier edge list can grow large", "Extra filtering for stale edges"],
    bestFor: "When you want Prim behavior driven directly by edge randomness.",
    interestingFact:
      "Compared with frontier-cell Prim, edge-based Prim can emphasize different local branching statistics.",
  },
  {
    id: "kruskal",
    name: "Randomized Kruskal",
    kind: "Generator",
    summary: "Carves walls by joining disjoint sets while avoiding cycles.",
    howItWorks: [
      "Treat each cell as its own set.",
      "Shuffle candidate walls (edges) between neighboring cells.",
      "If an edge connects two different sets, carve it and union the sets.",
      "Stop when all cells are in one connected set.",
    ],
    timeComplexity: "O(E α(V))",
    spaceComplexity: "O(V)",
    pros: ["Strong theoretical guarantees", "Uniform spanning-tree style behavior"],
    cons: ["Needs union-find", "Less intuitive than DFS/Prim"],
    bestFor: "When you want explicit disjoint-set control and predictable correctness.",
    interestingFact:
      "Union-find path compression makes practical performance very fast even on large grids.",
  },
  {
    id: "kruskal-loopy",
    name: "Kruskal (Loopy)",
    kind: "Generator",
    summary:
      "Runs classic Kruskal first, then reopens selected rejected edges to add controlled cycles.",
    howItWorks: [
      "Shuffle all grid edges and run disjoint-set Kruskal to build a spanning tree.",
      "Track edges rejected during tree growth because they would form cycles.",
      "Compute loop budget from loop-density target.",
      "Reopen rejected edges until the budget is exhausted.",
    ],
    timeComplexity: "O(E α(V)) + O(extraEdges)",
    spaceComplexity: "O(V + E)",
    pros: ["Predictable global loop density", "Clear two-phase behavior"],
    cons: ["Needs storing rejected edges", "Not a perfect maze"],
    bestFor: "Evenly distributed loops with a deterministic cycle budget.",
    interestingFact:
      "Because edges are globally shuffled first, extra cycles are spread broadly rather than clustered in one region.",
  },
  {
    id: "binary-tree",
    name: "Binary Tree",
    kind: "Generator",
    summary: "Each cell carves toward one of two preferred directions.",
    howItWorks: [
      "Visit cells in scan order.",
      "For each cell, carve either north or west when available.",
      "Edge cells carve only when the direction exists.",
      "Continue until all cells are processed.",
    ],
    timeComplexity: "O(V)",
    spaceComplexity: "O(1)",
    pros: ["Extremely fast", "Tiny memory footprint"],
    cons: ["Directional bias", "Predictable patterns"],
    bestFor: "High-speed generation and teaching directional bias effects.",
    interestingFact:
      "Its directional rule creates obvious diagonal flow patterns that are easy to recognize visually.",
  },
  {
    id: "sidewinder",
    name: "Sidewinder",
    kind: "Generator",
    summary: "Builds horizontal runs and occasionally links them upward.",
    howItWorks: [
      "Move across each row while extending a run to the east.",
      "Randomly decide to close the run.",
      "When closing, carve one north connection from a random cell in the run.",
      "Repeat per row.",
    ],
    timeComplexity: "O(V)",
    spaceComplexity: "O(1)",
    pros: ["Very fast", "Distinct corridor aesthetics"],
    cons: ["Visible row bias", "Less organic appearance"],
    bestFor: "Fast generation with intentional horizontal character.",
    interestingFact:
      "It is often paired with Binary Tree to show how tiny local rules create global maze style.",
  },
  {
    id: "aldous-broder",
    name: "Aldous-Broder",
    kind: "Generator",
    summary: "Uses a pure random walk and carves only on first visits.",
    howItWorks: [
      "Start from a random cell.",
      "Walk to a random neighbor each step.",
      "If that neighbor is unvisited, carve the edge and mark it visited.",
      "Stop after all cells are visited.",
    ],
    timeComplexity: "Expected O(V^2)",
    spaceComplexity: "O(V)",
    pros: ["Uniform spanning tree", "Conceptually minimal"],
    cons: ["Can be very slow", "Many non-carving steps"],
    bestFor: "Demonstrating random-walk behavior and uniform spanning tree theory.",
    interestingFact:
      "Despite being simple, it converges slowly because random walks revisit cells many times.",
  },
  {
    id: "hunt-and-kill",
    name: "Hunt-and-Kill",
    kind: "Generator",
    summary: "Alternates random walking with linear hunts for a new branch point.",
    howItWorks: [
      "Walk randomly until reaching a dead end.",
      "Scan for an unvisited cell adjacent to visited territory.",
      "Connect there and resume random walking.",
      "Finish when the scan finds no valid unvisited cell.",
    ],
    timeComplexity: "O(V^2) worst-case",
    spaceComplexity: "O(V)",
    pros: ["Interesting phase changes", "Good organic structure"],
    cons: ["Scanning phase can be expensive", "Slightly more bookkeeping"],
    bestFor: "Visual demos where algorithm phases should feel very different.",
    interestingFact:
      "The switch between hunt and kill phases is very visible and makes this algorithm great for education.",
  },
  {
    id: "growing-tree",
    name: "Growing Tree",
    kind: "Generator",
    summary:
      "Generalized family that blends DFS-like and Prim-like behavior via selection policy.",
    howItWorks: [
      "Keep a list of active cells.",
      "Select one active cell using a strategy (newest, random, or mixed).",
      "Carve to one unvisited neighbor if possible; otherwise remove the active cell.",
      "Continue until no active cells remain.",
    ],
    timeComplexity: "O(V)",
    spaceComplexity: "O(V)",
    pros: ["Highly tunable style", "Good compromise between long corridors and branching"],
    cons: ["Selection policy impacts style heavily", "Less canonical than pure DFS/Prim"],
    bestFor: "When you want one algorithm knob to dial corridor-vs-branch behavior.",
    interestingFact:
      "Using newest-only turns it into recursive backtracker; random-only makes it feel close to Prim.",
  },
  {
    id: "bfs-tree",
    name: "Randomized BFS Tree",
    kind: "Generator",
    summary: "Builds a spanning tree layer-by-layer from a queue frontier.",
    howItWorks: [
      "Choose a start cell and enqueue it.",
      "Pop cells in BFS order and inspect neighbors.",
      "For each unvisited neighbor, carve to it and enqueue it.",
      "Continue until queue is exhausted.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Very stable progression", "Naturally broad, wave-like growth"],
    cons: ["Can look less organic than DFS variants", "Needs queue/frontier bookkeeping"],
    bestFor: "Clear breadth-first generation visuals and predictable expansion fronts.",
    interestingFact:
      "Unlike Prim, this variant commits tree parents by discovery order, creating BFS-depth layers.",
  },
  {
    id: "eller",
    name: "Eller",
    kind: "Generator",
    summary: "Builds the maze one row at a time using dynamic disjoint sets.",
    howItWorks: [
      "Assign set ids across the current row.",
      "Randomly join adjacent cells with different set ids.",
      "For each set, carve at least one vertical connection downward.",
      "On the final row, force all remaining disjoint sets to merge.",
    ],
    timeComplexity: "O(V) expected",
    spaceComplexity: "O(width)",
    pros: ["Streaming-friendly", "Memory-efficient for tall mazes"],
    cons: ["Row-wise bias can be visible", "Implementation is more stateful than DFS/Prim"],
    bestFor: "Generating large mazes where memory proportional to width is preferred.",
    interestingFact:
      "Eller is one of the few classic perfect-maze algorithms that does not require full-grid state history.",
  },
  {
    id: "wilson",
    name: "Wilson",
    kind: "Generator",
    summary: "Creates a uniform spanning tree using loop-erased random walks.",
    howItWorks: [
      "Start with one cell in the tree.",
      "Pick an unvisited cell and perform a random walk.",
      "Erase loops in the walk as they form (loop-erased random walk).",
      "When the walk hits the existing tree, carve the whole walk into the tree.",
    ],
    timeComplexity: "Expected polynomial; often higher than DFS/Prim",
    spaceComplexity: "O(V)",
    pros: ["Uniform spanning tree output", "Strong theoretical guarantees"],
    cons: ["Can be slower", "Walk-loop bookkeeping is heavier"],
    bestFor: "When statistical fairness of generated spanning trees matters.",
    interestingFact:
      "Wilson and Aldous-Broder both generate uniform spanning trees, but Wilson is usually much faster in practice.",
  },
  {
    id: "houston",
    name: "Houston (AB + Wilson)",
    kind: "Generator",
    summary: "Hybrid that starts with Aldous-Broder then switches to Wilson for speed.",
    howItWorks: [
      "Run Aldous-Broder random walk for an initial visited fraction.",
      "Use the visited cells as an initial tree.",
      "Switch to Wilson loop-erased walks for the remaining unvisited cells.",
      "Finish when every cell is merged into the tree.",
    ],
    timeComplexity: "Expected faster than pure AB, near Wilson in late stage",
    spaceComplexity: "O(V)",
    pros: ["Practical speed boost", "Retains random-walk flavor early on"],
    cons: ["More implementation complexity", "Hybrid behavior is less canonical"],
    bestFor: "Balancing visual random-walk behavior with practical completion speed.",
    interestingFact:
      "Houston is a known optimization strategy specifically meant to mitigate Aldous-Broder's long tail.",
  },
  {
    id: "recursive-division",
    name: "Recursive Division",
    kind: "Generator",
    summary: "Creates a maze by adding split walls with one opening per division.",
    howItWorks: [
      "Start from an open field (internal walls removed).",
      "Pick horizontal or vertical orientation per region.",
      "Add a dividing wall and keep one random gap.",
      "Recurse into both child regions until indivisible.",
    ],
    timeComplexity: "O(V log V) typical",
    spaceComplexity: "O(log V) recursion + patch batches",
    pros: ["Distinct architectural look", "Fast wall-adding style"],
    cons: ["Can look structured", "Less organic than random walkers"],
    bestFor: "When you want blocky, room-like visual structure.",
    interestingFact:
      "This is the canonical wall-adder among classic maze generators.",
  },
  {
    id: "recursive-division-loopy",
    name: "Recursive Division (Multi-Gap)",
    kind: "Generator",
    summary:
      "Recursive-division variant that keeps multiple doorway gaps per divider based on loop density.",
    howItWorks: [
      "Start from a fully open field.",
      "For each split wall, keep at least one doorway gap.",
      "Add extra doorway gaps proportional to configured loop density.",
      "Recurse through child regions until no more splits are possible.",
    ],
    timeComplexity: "O(V log V) typical",
    spaceComplexity: "O(log V) recursion + patch batches",
    pros: ["Architectural style with route multiplicity", "Direct loop-density control"],
    cons: ["Can become too open at high density", "Not a perfect maze"],
    bestFor: "Room-like layouts where multiple corridor choices are desired.",
    interestingFact:
      "Adding just one extra doorway per divider can quickly increase alternate shortest routes across the layout.",
  },
  {
    id: "bsp",
    name: "Binary Space Partitioning (BSP)",
    kind: "Generator",
    summary: "Recursively partitions space into regions and connects region trees with bridge edges.",
    howItWorks: [
      "Recursively split a rectangular region horizontally or vertically.",
      "Generate each child region subtree recursively.",
      "Choose one connector crossing the split boundary.",
      "Carve that connector so both child trees become one component.",
    ],
    timeComplexity: "O(V log V) typical recursive partitioning",
    spaceComplexity: "O(log V) recursion + O(V) edge plan",
    pros: ["Structured dungeon-like topology", "Deterministic partition hierarchy"],
    cons: ["Can look too geometric", "Less organic than walk-based generators"],
    bestFor: "Room/partition-flavored maze layouts and dungeon prototyping.",
    interestingFact:
      "BSP is commonly used in roguelike map generation where rooms and corridors are assembled from a split tree.",
  },
  {
    id: "blobby-recursive-subdivision",
    name: "Blobby Recursive Subdivision",
    kind: "Generator",
    summary: "Recursive subdivision variant that uses organic connected blob partitions instead of strict straight cuts.",
    howItWorks: [
      "Select two seeds inside a connected region.",
      "Grow two blob partitions from those seeds until the region is assigned.",
      "Recurse into each blob partition and build local subtrees.",
      "Carve one connector between both blob partitions to preserve tree connectivity.",
    ],
    timeComplexity: "O(V log V) typical, with local fallback O(V)",
    spaceComplexity: "O(V)",
    pros: ["More organic than strict BSP/recursive-division", "Retains recursive controllability"],
    cons: ["More complex split validation", "Harder to reason about visually"],
    bestFor: "Hybrid aesthetic between structured partitioning and cave-like flow.",
    interestingFact:
      "Blob-first partitioning reduces long ruler-straight wall artifacts common in axis-aligned subdivision.",
  },
  {
    id: "prim-true",
    name: "Prim (True Frontier Edges - Random Prim)",
    kind: "Generator",
    summary: "Alias of Prim (Frontier Edges), kept for naming compatibility.",
    howItWorks: [
      "Delegate generation to Prim (Frontier Edges).",
      "Sample random frontier edges from visited to unvisited cells.",
      "Carve accepted edges and expand the frontier.",
      "Finish when no valid frontier edges remain.",
    ],
    timeComplexity: "O(E) expected",
    spaceComplexity: "O(E)",
    pros: ["Familiar naming for edge-frontier Prim users", "Exactly matches canonical runtime behavior"],
    cons: ["Not a distinct implementation", "Behavior changes only when Prim (Frontier Edges) changes"],
    bestFor: "Users looking for edge-frontier Prim under a more explicit label.",
    interestingFact:
      "In this codebase, prim-true is a direct alias of prim-frontier-edges.",
  },
  {
    id: "prim-simplified",
    name: "Prim (Simplified - Randomized Prim)",
    kind: "Generator",
    summary: "Alias of Randomized Prim (frontier-cell variant) with alternate naming.",
    howItWorks: [
      "Delegate generation to Randomized Prim.",
      "Track frontier cells near visited territory.",
      "Connect each selected frontier cell to visited space.",
      "Repeat until the frontier is exhausted.",
    ],
    timeComplexity: "O(V) expected",
    spaceComplexity: "O(V)",
    pros: ["Alternative naming for the same implementation", "Exactly matches Randomized Prim behavior"],
    cons: ["Not a distinct algorithm", "Can be confused with separate Prim variants"],
    bestFor: "Users expecting a simplified-Prim label without changing runtime behavior.",
    interestingFact:
      "In this codebase, prim-simplified is a direct alias of prim.",
  },
  {
    id: "prim-modified",
    name: "Prim (Modified)",
    kind: "Generator",
    summary: "Random-active-cell variant close to Growing Tree random policy.",
    howItWorks: [
      "Keep active in-maze cells.",
      "Select one active cell uniformly at random.",
      "Carve to a random unvisited neighbor if possible.",
      "Drop active cells that have no remaining unvisited neighbors.",
    ],
    timeComplexity: "O(V)",
    spaceComplexity: "O(V)",
    pros: ["Flexible texture", "Simple random policy"],
    cons: ["Style depends on active-list evolution", "Not uniform"],
    bestFor: "Middle ground between Prim-like and DFS-like growth.",
    interestingFact:
      "This policy is one endpoint of the broader Growing Tree algorithm family.",
  },
  {
    id: "growing-forest",
    name: "Growing Forest",
    kind: "Generator",
    summary: "Grows multiple trees in parallel, then merges them into one maze.",
    howItWorks: [
      "Seed several trees across the grid.",
      "Grow each tree into nearby unvisited cells.",
      "When growth saturates, collect boundary edges between trees.",
      "Union tree components with boundary carves until one tree remains.",
    ],
    timeComplexity: "O(V + E α(V))",
    spaceComplexity: "O(V)",
    pros: ["Distinct multi-origin growth", "Good global variety"],
    cons: ["More bookkeeping", "Harder to reason about than single-tree growth"],
    bestFor: "Visualizations emphasizing concurrent growth fronts.",
    interestingFact:
      "Forest merge phase is effectively a component-union process similar to Kruskal.",
  },
  {
    id: "unicursal",
    name: "Unicursal",
    kind: "Generator",
    summary: "Builds a single non-branching path through the full grid.",
    howItWorks: [
      "Create a serpentine Hamiltonian-style ordering of cells.",
      "Carve between consecutive cells in that ordering.",
      "Continue until all cells are connected in one route.",
    ],
    timeComplexity: "O(V)",
    spaceComplexity: "O(V)",
    pros: ["No branch ambiguity", "Very readable path structure"],
    cons: ["Not a branching maze feel", "Low replay diversity"],
    bestFor: "Labyrinth-style experiences and path-only demonstrations.",
    interestingFact:
      "Unicursal structures have exactly one route and no junction choices.",
  },
  {
    id: "fractal-tessellation",
    name: "Fractal Tessellation",
    kind: "Generator",
    summary: "Recursively forms quadrant trees and stitches them with three bridges.",
    howItWorks: [
      "Split region into quadrants recursively.",
      "Generate subtree edges inside each quadrant.",
      "Sample cross-boundary connector candidates.",
      "Select three connectors that unify quadrants without cycles.",
    ],
    timeComplexity: "O(V log V) typical",
    spaceComplexity: "O(V)",
    pros: ["Recursive self-similar texture", "Strong visual identity"],
    cons: ["Can look regular", "More implementation complexity"],
    bestFor: "Fractal-style maze aesthetics and recursive demos.",
    interestingFact:
      "Using exactly three inter-quadrant links preserves tree structure at each merge.",
  },
  {
    id: "cellular-automata",
    name: "Cellular Automata (Cave-Biased)",
    kind: "Generator",
    summary: "Uses a smoothed CA mask to bias spanning-tree carving decisions.",
    howItWorks: [
      "Initialize random binary cave mask.",
      "Run CA smoothing iterations over the mask.",
      "Grow a spanning tree while preferring neighbors with similar cave state.",
      "Backtrack when stuck until all cells are carved.",
    ],
    timeComplexity: "O(V) generation + O(V) mask smoothing",
    spaceComplexity: "O(V)",
    pros: ["Organic local texture bias", "Still deterministic and step-friendly"],
    cons: ["Not pure cave generation", "Requires extra precomputation"],
    bestFor: "Hybrid cave-like style without losing spanning-tree guarantees.",
    interestingFact:
      "CA-inspired bias lets one algorithm bridge classic mazes and dungeon-like visuals.",
  },
  {
    id: "maze-ca",
    name: "Maze CA (B3/S12345)",
    kind: "Generator",
    summary:
      "Applies Maze-rule cellular automata as a structural bias, then carves a deterministic spanning tree.",
    howItWorks: [
      "Initialize a random binary field.",
      "Evolve the field with Maze rule B3/S12345 for fixed iterations.",
      "Use resulting states to bias DFS-style carving toward same-state neighbors.",
      "Backtrack when needed until a full spanning tree is carved.",
    ],
    timeComplexity: "O(V) carving + O(V) CA iterations",
    spaceComplexity: "O(V)",
    pros: ["Research-rule inspired texture", "Deterministic seeded behavior"],
    cons: ["Hybridized (not pure CA corridor extraction)", "Mask quality depends on iteration settings"],
    bestFor: "Including canonical CA rule families in a step-wise perfect-maze runtime.",
    interestingFact:
      "The classical Maze CA is usually run as full-grid evolution; here it is adapted as a guidance field for tree carving.",
  },
  {
    id: "mazectric-ca",
    name: "Mazectric CA (B3/S1234)",
    kind: "Generator",
    summary:
      "Mazectric-rule variant with slightly stricter survival behavior, used as a carving bias field.",
    howItWorks: [
      "Initialize a random binary field.",
      "Evolve with Mazectric rule B3/S1234 for fixed iterations.",
      "Bias DFS-style carving to neighbors with matching evolved state.",
      "Complete by backtracking until every cell is visited.",
    ],
    timeComplexity: "O(V) carving + O(V) CA iterations",
    spaceComplexity: "O(V)",
    pros: ["Distinct from Maze-rule mask behavior", "Deterministic and animation-friendly"],
    cons: ["Still a hybrid adaptation", "Can appear similar to Maze CA on small grids"],
    bestFor: "Comparative demos between Maze and Mazectric cellular rule families.",
    interestingFact:
      "Mazectric typically favors straighter structures than Maze in unconstrained CA outputs.",
  },
  {
    id: "braid",
    name: "Braid (Dead-End Reduction)",
    kind: "Generator",
    summary:
      "Builds a perfect maze first, then removes dead ends by opening selected extra connections.",
    howItWorks: [
      "Generate a base perfect maze (spanning tree).",
      "Collect dead-end cells and process them in shuffled order.",
      "For each remaining dead end, open one closed wall to a nearby passage.",
      "Stop once dead-end pass is exhausted or target reduction is reached.",
    ],
    timeComplexity: "O(V) after base generation",
    spaceComplexity: "O(V)",
    pros: ["Eliminates many cul-de-sacs", "Creates harder loop-rich navigation"],
    cons: ["Not a perfect maze", "Wall-follower strategies become unreliable"],
    bestFor: "Loop-heavy mazes and solver robustness comparisons.",
    interestingFact:
      "Braiding is commonly treated as a post-process transform rather than a standalone carve algorithm.",
  },
  {
    id: "weave-growing-tree",
    name: "Weave Growing Tree",
    kind: "Generator",
    summary:
      "Growing-tree base maze with over/under crossings introduced as non-junction weave tunnels.",
    howItWorks: [
      "Generate a base tree maze using growing-tree policy.",
      "Scan interior straight-corridor cells for weave eligibility.",
      "Mark crossing orientation at selected cells.",
      "Create tunnel links between opposite neighbors to model the underpass channel.",
    ],
    timeComplexity: "O(V) base + O(V) crossing scan",
    spaceComplexity: "O(V)",
    pros: ["Pseudo-3D over/under aesthetics", "Crossings avoid 4-way junction ambiguity"],
    cons: ["More complex rendering/traversal model", "Some local solvers are incompatible"],
    bestFor: "Weave puzzle styles and topology-aware solver comparisons.",
    interestingFact:
      "Weave mazes are often represented by layered traversal states even when drawn on a 2D grid.",
  },
  {
    id: "vortex",
    name: "Vortex Maze (Xu/Kaplan-inspired DFS)",
    kind: "Generator",
    summary: "Swirl-biased depth-first carving guided by local vortex centers.",
    howItWorks: [
      "Sample several vortex centers across the grid.",
      "Run a DFS-style carve with backtracking stack.",
      "Score candidate neighbors by tangent direction around nearest center.",
      "Prefer moves that continue local spiral flow while preserving spanning-tree rules.",
    ],
    timeComplexity: "O(V)",
    spaceComplexity: "O(V)",
    pros: ["Distinct spiral visual texture", "Deterministic with seeded randomness"],
    cons: ["Heuristic-biased look may reduce uniformity", "More tuning-sensitive than vanilla DFS"],
    bestFor: "High-obfuscation or artistic maze styles with curved-flow perception.",
    interestingFact:
      "Vortex-style constructions are designed to increase perceptual difficulty by packing locally parallel turning structures.",
  },
  {
    id: "origin-shift",
    name: "Origin Shift",
    kind: "Generator",
    summary: "Rewires a rooted spanning tree by repeatedly shifting the root.",
    howItWorks: [
      "Start from an initial rooted spanning tree.",
      "Pick a neighbor of the current root.",
      "Detach that neighbor from its old parent edge.",
      "Connect old root to the neighbor and promote neighbor as new root.",
    ],
    timeComplexity: "O(V + S), where S is shift count",
    spaceComplexity: "O(V)",
    pros: ["Unique dynamic rewiring animation", "Keeps tree connectivity throughout"],
    cons: ["Less intuitive than carve-from-walls methods", "Requires parent-edge tracking"],
    bestFor: "Modern/experimental generator comparisons.",
    interestingFact:
      "Each shift performs a local edge swap while preserving a valid spanning tree.",
  },
  {
    id: "reverse-delete",
    name: "Reverse-Delete",
    kind: "Generator",
    summary: "Begins fully open, then adds walls back only when connectivity is preserved.",
    howItWorks: [
      "Open all internal walls to start from a fully connected grid graph.",
      "Process candidate edges in randomized order.",
      "For each edge, test whether endpoints remain connected without that edge.",
      "If an alternate route exists, remove the edge by restoring that wall.",
    ],
    timeComplexity: "O(E * (V + E)) with bridge checks",
    spaceComplexity: "O(V)",
    pros: ["Strong correctness intuition", "Distinct wall-adding visual style"],
    cons: ["More expensive than carve-forward methods", "Needs repeated connectivity checks"],
    bestFor: "Educational comparisons between edge-removal and edge-addition paradigms.",
    interestingFact:
      "Reverse-Delete is the conceptual mirror image of Kruskal: it removes non-bridge edges instead of adding acyclic edges.",
  },
  {
    id: "boruvka",
    name: "Randomized Boruvka",
    kind: "Generator",
    summary: "Builds a maze in rounds by merging components through cheapest outgoing edges.",
    howItWorks: [
      "Treat each cell as its own component.",
      "Assign randomized edge priorities and find each component's best outgoing edge.",
      "Carve all selected non-cycling edges in one round.",
      "Repeat until a single connected component remains.",
    ],
    timeComplexity: "O(E log V) expected rounds with union-find",
    spaceComplexity: "O(V + E)",
    pros: ["Round-based growth is visually distinctive", "Efficient component convergence"],
    cons: ["Heavier bookkeeping than DFS/Prim", "Less common in maze tooling"],
    bestFor: "Comparing MST families and parallel-style component merging behavior.",
    interestingFact:
      "Boruvka predates Kruskal and Prim and naturally lends itself to parallel implementations.",
  },
  {
    id: "resonant-phase-lock",
    name: "Resonant Phase-Lock (Noise-Weighted Growing Tree)",
    kind: "Generator",
    summary:
      "Builds a spanning tree by choosing frontier cells using a self-updating resonance field derived from synthetic wave interference.",
    howItWorks: [
      "Generate a bounded interference phase field from multiple radial + directional wave emitters.",
      "Seed one root cell, then maintain a classic visited/unvisited frontier boundary.",
      "For each frontier candidate, score the best visited parent by phase alignment and local field continuity.",
      "Choose the globally best frontier candidate, carve that parent edge, and assign the new cell a blended phase.",
      "Emit a local resonance pulse that re-weights nearby frontier cells before the next pick.",
      "Repeat until all cells join one connected tree.",
    ],
    timeComplexity: "O(V²) with full frontier rescoring per step",
    spaceComplexity: "O(V)",
    pros: [
      "Creates coherent macro-structures without strict geometric partitioning",
      "Dynamic pulse feedback gives noticeably different flow than static-weight Prim variants",
      "Deterministic and tree-safe under seeded execution",
    ],
    cons: [
      "More arithmetic-heavy than baseline DFS/Prim",
      "Frontier rescoring is slower than O(V)-style generators",
    ],
    bestFor:
      "Experimental maze aesthetics where you want coherent wave-like structure but still need a perfect planar maze.",
    interestingFact:
      "This project-specific algorithm combines interference synthesis and phase-entrainment feedback inside a strict spanning-tree frontier loop. Invented in this project by Codex.",
  },
  {
    id: "erosion",
    name: "Erosion (Hydraulic)",
    kind: "Generator",
    summary:
      "Simulates water flowing downhill across a heightmap; erosion feedback creates dendritic river-network branching.",
    howItWorks: [
      "Generate a smooth heightmap from random control points using inverse-distance weighting.",
      "The lowest cell becomes the river outlet (tree root).",
      "Each step pops the lowest-elevation frontier cell (water flows downhill first).",
      "Connect it to the tree-neighbor with steepest descent.",
      "Erode: lower heights of unvisited neighbors, making cells near existing rivers more attractive.",
      "The erosion feedback creates self-reinforcing river capture, producing hierarchical dendritic patterns.",
    ],
    timeComplexity: "O(V²) with linear frontier scan",
    spaceComplexity: "O(V)",
    pros: [
      "Produces unique dendritic (river-network) branching patterns",
      "Self-modifying priorities create hierarchical passage structure",
      "Visually distinctive — unlike any other maze generator",
    ],
    cons: [
      "O(V²) due to linear frontier scan",
      "Pattern depends on heightmap quality",
    ],
    bestFor:
      "Generating mazes with natural, river-like branching where main corridors collect tributaries.",
    interestingFact:
      "This is a novel algorithm that combines terrain hydrology with spanning-tree construction. The erosion feedback mechanism — where carving a passage lowers nearby terrain — has no precedent in published maze generation literature. Invented in this project by Claude.",
  },
  {
    id: "quantum-seismogenesis",
    name: "Quantum Seismogenesis (Multi-Source Prim's)",
    kind: "Generator",
    summary:
      "Accumulates synthetic stress and propagates fracture tips that carve only when they connect disjoint components.",
    howItWorks: [
      "Track per-cell stress and union-find connectivity across all cells.",
      "When no fracture is active, add random stress pulses to random cells until one ignites.",
      "Process one active fracture tip: rank neighbors by stress and attempt to carve the first non-cycling edge.",
      "On a successful carve, transfer stress toward the new tip and keep propagating the fracture front.",
      "If a tip cannot carve without creating a cycle, dissipate it and wait for the next ignition.",
    ],
    timeComplexity: "O(V²) expected due repeated stress diffusion and frontier rescoring",
    spaceComplexity: "O(V)",
    pros: [
      "Produces sharp branching phases with clear fracture-wave behavior",
      "Union-find keeps output cycle-safe (perfect maze)",
      "Distinct visual rhythm versus standard frontier methods",
    ],
    cons: [
      "More stateful and arithmetic-heavy than classic generators",
      "Performance can lag on very large grids",
    ],
    bestFor:
      "Experimental generation where you want tectonic crack-like growth rather than smooth expansion fronts.",
    interestingFact:
      "This project-specific generator blends stress-threshold ignition with spanning-tree constraints, so fractures look chaotic while still guaranteeing connectivity without loops. Invented in this project by Gemini.",
  },
  {
    id: "mycelial-anastomosis",
    name: "Mycelial Anastomosis (Multi-Source Kruskal's & Random Walk)",
    kind: "Generator",
    summary:
      "Simulates fungal hyphae that grow from multiple spores, branch, and occasionally merge separate growth networks.",
    howItWorks: [
      "Seed multiple starting spores and treat each as an active growth tip.",
      "Pick a random active tip and shuffle its neighbors to choose a growth direction.",
      "If an unvisited neighbor is found, carve into it and continue from the new tip (sometimes branch).",
      "If a visited neighbor belongs to a different union-find component, carve an anastomosis merge edge.",
      "Retire dead-end tips and spawn fallback growth only when all tips die before completion.",
    ],
    timeComplexity: "O(V) expected with near-constant-time union-find merges",
    spaceComplexity: "O(V)",
    pros: [
      "Multi-source growth creates organic, network-like structure",
      "Branching and merging phases are visually expressive",
      "Maintains perfect-maze guarantees via component checks",
    ],
    cons: [
      "Behavior tuning is more complex than single-frontier algorithms",
      "Output style can vary strongly with branching probability",
    ],
    bestFor:
      "Organic maze aesthetics that resemble biological growth and network fusion.",
    interestingFact:
      "Anastomosis is a real fungal behavior where separate hyphae fuse; this algorithm adapts that idea into cycle-safe maze construction. Invented in this project by Gemini.",
  },
  {
    id: "counterfactual-cycle-annealing",
    name: "Counterfactual Cycle Annealing (Simulated Graph Annealing)",
    kind: "Generator",
    summary:
      "Starts from a valid spanning tree, then performs objective-driven edge swaps (add chord, remove cycle edge) under simulated annealing.",
    howItWorks: [
      "Generate a seed perfect maze using randomized depth-first tree growth.",
      "Define per-cell target branching degrees plus per-edge affinity scores.",
      "Each annealing step proposes one closed edge near high local stress.",
      "That proposal forms a virtual cycle; evaluate every removable edge on the induced cycle path.",
      "Apply the best swap if it improves local energy, or sometimes accept worse swaps early while temperature is high.",
      "Because each accepted move adds one edge and removes one cycle edge, the maze remains connected and acyclic.",
    ],
    timeComplexity:
      "O(KV) typical, where K is swap budget and each step includes tree-path search",
    spaceComplexity: "O(V + E)",
    pros: [
      "Unique rewiring behavior unlike one-pass growth algorithms",
      "Preserves perfect-maze guarantees throughout optimization",
      "Can sculpt corridor/branching texture without rebuilding from scratch",
    ],
    cons: [
      "More stateful than classic generators",
      "Path search inside each swap attempt adds overhead",
    ],
    bestFor:
      "Experimental generation where you want iterative, optimization-style morphology instead of single-pass carving.",
    interestingFact:
      "This generator treats maze construction as local counterfactual editing: every move evaluates what would happen if one edge were replaced by another before committing. Invented in this project by Codex.",
  },
  {
    id: "sandpile-avalanche",
    name: "Sandpile Avalanche (Self-Organized Criticality)",
    kind: "Generator",
    summary:
      "Builds a maze through self-organized criticality: sand grains accumulate and topple in cascading avalanches that carve passages at component boundaries.",
    howItWorks: [
      "Pre-seed each cell with 1–3 sand grains, placing the system near criticality.",
      "Each step drops one grain on a random cell. If its height reaches 4, it topples: −4 grains to itself, +1 to each neighbor.",
      "Toppling can cascade — neighbors pushed to 4 also topple, creating avalanches of any size.",
      "When a topple sends sand across a union-find component boundary, carve a passage and merge the components.",
      "After a carve drought, bias grain drops toward boundary cells to accelerate the tail phase.",
    ],
    timeComplexity: "O(V²) expected due to repeated avalanche resolution and boundary scanning",
    spaceComplexity: "O(V)",
    pros: [
      "Genuinely emergent: power-law avalanche size distribution creates unpredictable drama",
      "Simplest possible rules — drop, topple at 4, carve on boundary crossing",
      "Grounded in real complexity science (Bak–Tang–Wiesenfeld 1987)",
    ],
    cons: [
      "Variable step count — some drops do nothing, others trigger massive cascades",
      "Tail phase can slow without the acceleration heuristic",
    ],
    bestFor:
      "Watching self-organized criticality build a maze through emergent avalanche dynamics.",
    interestingFact:
      "The Abelian sandpile is the canonical model of self-organized criticality — systems that naturally evolve to a state where small inputs can trigger chain reactions of any scale. This is the first application of sandpile dynamics to maze generation. Invented in this project by Claude.",
  },
  {
    id: "reaction-diffusion",
    name: "Reaction-Diffusion (Turing)",
    kind: "Generator",
    summary: "Simulates Gray-Scott chemical kinetics to naturally grow Turing patterns.",
    howItWorks: [
      "Seed chemicals A and B with some noise.",
      "Simulate diffusion and reaction using the Gray-Scott model.",
      "Threshold the resulting continuous field into a binary passage mask.",
      "Ensure spanning-tree connectivity with a randomized bridge builder.",
    ],
    timeComplexity: "O(V * steps) for chemistry simulation",
    spaceComplexity: "O(V) for continuous fields",
    pros: ["Truly organic, alien-looking mazes", "Incredible visualization of pattern formation"],
    cons: ["Slower than graph algorithms", "Requires post-processing to guarantee spanning"],
    bestFor: "Artistic, cellular-automata or chemistry simulations producing mazes.",
    interestingFact:
      "Turing patterns explain how animal skins, like zebra stripes, get their complex shapes naturally. Invented in this project by Gemini.",
  },
  {
    id: "ant-colony",
    name: "Ant Colony Excavation",
    kind: "Generator",
    summary: "Simulates pheromone-guided ants probabilistically digging out a spanning tree.",
    howItWorks: [
      "Spawn active ants that move across the grid leaving pheromones.",
      "Ants heavily prefer moving to cells with high pheromones.",
      "When an ant moves between disjoint union-find sets, it carves a tunnel.",
      "Pheromones gradually evaporate, keeping the exploration dynamic.",
    ],
    timeComplexity: "O(V * steps) dependent on ant exploration",
    spaceComplexity: "O(V)",
    pros: ["Biologically inspired organic growth", "Produces distinct arterial structures"],
    cons: ["Can take longer to finish if ants get stuck", "Requires union-find components tracking"],
    bestFor: "Demonstrating swarm intelligence applied to generative creation.",
    interestingFact:
      "This turns the classic Ant Colony Optimization solver upside down, using ants to *build* the maze instead of solve it. Invented in this project by Gemini.",
  },
  {
    id: "ising-model",
    name: "Magnetic Spin Crystallization (Ising-Weighted Kruskal's)",
    kind: "Generator",
    summary: "Uses simulated annealing with an Ising model to crystallize a random grid.",
    howItWorks: [
      "Start with a hot grid of random spins.",
      "Attempt to flip spins to minimize an energy function preferring straight corridors.",
      "Cool the temperature down over time (Metropolis-Hastings).",
      "Feed the final cooled spin weights into a Kruskal builder.",
    ],
    timeComplexity: "O(V * steps) for annealing",
    spaceComplexity: "O(V)",
    pros: ["Mathematical crystallization visuals", "Tunable using Hamiltonian energy functions"],
    cons: ["Heuristic-based, occasionally unpredictable weights"],
    bestFor: "Physics-based statistical mechanics demonstrations.",
    interestingFact:
      "The Ising model is fundamental in physics for simulating ferromagnetism and phase transitions. Invented in this project by Gemini.",
  },
  {
    id: "bfs",
    name: "Breadth-First Search (BFS)",
    kind: "Solver",
    summary: "Expands in layers and guarantees shortest path in unweighted mazes.",
    howItWorks: [
      "Push start cell into a queue.",
      "Pop in FIFO order and visit neighbors.",
      "Record each neighbor's parent when first discovered.",
      "When goal is reached, reconstruct path via parents.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Optimal path for unit weights", "Simple and robust"],
    cons: ["Can explore many irrelevant nodes", "Large frontier on wide-open maps"],
    bestFor: "Reliable shortest path on unweighted grids.",
    interestingFact:
      "BFS is equivalent to Dijkstra when every edge has identical weight.",
  },
  {
    id: "dfs",
    name: "Depth-First Search (DFS)",
    kind: "Solver",
    summary: "Follows one branch deeply before backing up.",
    howItWorks: [
      "Push start cell onto a stack.",
      "Pop and explore a neighbor branch deeply.",
      "Track discovery parents for reconstruction.",
      "Backtrack naturally when stack unwinds.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Very low overhead", "Strong step-by-step visual clarity"],
    cons: ["No shortest-path guarantee", "Can take long detours"],
    bestFor: "Showing exploratory behavior rather than shortest paths.",
    interestingFact:
      "On tree mazes (perfect mazes), DFS still finds the unique path but may explore much more first.",
  },
  {
    id: "astar",
    name: "A* Search",
    kind: "Solver",
    summary: "Combines actual cost and heuristic distance to guide exploration.",
    howItWorks: [
      "Maintain open set prioritized by f(n)=g(n)+h(n).",
      "Expand the cell with lowest estimated total cost.",
      "Relax neighbors if a better g-cost is found.",
      "Stop at goal and reconstruct via parents.",
    ],
    timeComplexity: "O(E) to O(E log V), depending on priority structure",
    spaceComplexity: "O(V)",
    pros: ["Usually much faster than BFS", "Optimal with admissible heuristic"],
    cons: ["Needs heuristic tuning", "Bookkeeping heavier than BFS/DFS"],
    bestFor: "Fast near-optimal routing on grid mazes.",
    interestingFact:
      "Manhattan distance is a natural heuristic for 4-directional grids.",
  },
  {
    id: "astar-euclidean",
    name: "A* (Euclidean)",
    kind: "Solver",
    summary: "A* variant using straight-line distance heuristic.",
    howItWorks: [
      "Score candidates with f(n)=g(n)+h(n), where h is Euclidean distance.",
      "Expand the lowest f-score node.",
      "Relax neighbors with improved g-cost and update parents.",
      "Stop and reconstruct when reaching goal.",
    ],
    timeComplexity: "O(E) to O(E log V), depending on queue",
    spaceComplexity: "O(V)",
    pros: ["Admissible and consistent on grid movement", "Often smooth directional guidance"],
    cons: ["Can expand more than Manhattan A* on 4-neighbor grids", "Still more bookkeeping than BFS"],
    bestFor: "Comparing heuristic behavior and exploring geometric distance cues.",
    interestingFact:
      "Euclidean is tighter for continuous geometry, while Manhattan better matches axis-only moves.",
  },
  {
    id: "weighted-astar",
    name: "Weighted A*",
    kind: "Solver",
    summary:
      "Biases A* harder toward the heuristic for more aggressive search on unit-cost maze edges.",
    howItWorks: [
      "Use f(n)=g(n)+w*h(n) with w>1.",
      "Expand the node with smallest weighted estimate.",
      "Continue relaxing neighbors and updating parents.",
      "Return reconstructed path when goal is dequeued.",
    ],
    timeComplexity: "Often faster than A* in practice",
    spaceComplexity: "O(V)",
    pros: ["Lower exploration count", "Good speed at high grid sizes"],
    cons: ["Can lose optimality", "Quality depends on weight"],
    bestFor:
      "When responsiveness matters more than guaranteed shortest path, without changing maze edge weights.",
    interestingFact:
      "Weighted A* is common in games and robotics where near-optimal is acceptable for speed.",
  },
  {
    id: "dijkstra",
    name: "Dijkstra",
    kind: "Solver",
    summary: "Uniform-cost expansion from the source, optimal for nonnegative weights.",
    howItWorks: [
      "Initialize start with distance 0 and others with infinity.",
      "Expand the currently known minimum-distance node.",
      "Relax each outgoing neighbor distance.",
      "Stop when goal is finalized.",
    ],
    timeComplexity: "O(E) to O(E log V), depending on queue",
    spaceComplexity: "O(V)",
    pros: ["Optimal", "Generalizes to weighted edges"],
    cons: ["More work than BFS on unit weights", "No heuristic acceleration"],
    bestFor: "Reference optimal solver and weighted-path baselines.",
    interestingFact:
      "Dijkstra published his algorithm in 1956 and reportedly designed it in about twenty minutes.",
  },
  {
    id: "bellman-ford",
    name: "Bellman-Ford",
    kind: "Solver",
    summary:
      "Relaxes all open edges in repeated passes until no shorter distances remain.",
    howItWorks: [
      "Initialize start distance to 0 and all others to infinity.",
      "Run full relaxation passes over every open edge using previous-pass distances.",
      "Update parent links whenever a shorter path to a node is found.",
      "Stop when a pass makes no improvements and reconstruct the path.",
    ],
    timeComplexity: "O(VE)",
    spaceComplexity: "O(V)",
    pros: ["Provably optimal with nonnegative weights", "Simple global convergence criterion"],
    cons: [
      "More work than BFS/Dijkstra on unweighted mazes",
      "Global pass updates are still heavier than frontier-only methods",
    ],
    bestFor: "Reference correctness checks and shortest-path algorithm comparisons.",
    interestingFact:
      "This visualizer uses pass-snapshot relaxation so Bellman-Ford progression remains visible instead of collapsing in one cascaded pass.",
  },
  {
    id: "iterative-deepening-dfs",
    name: "Iterative Deepening DFS (IDDFS)",
    kind: "Solver",
    summary: "Runs depth-limited DFS repeatedly with increasing depth limits.",
    howItWorks: [
      "Start with depth limit 0.",
      "Perform DFS constrained to the current limit.",
      "If goal is not found, increase limit and restart from the start node.",
      "Reconstruct the path as soon as a depth-limited run reaches the goal.",
    ],
    timeComplexity: "O(b^d) node expansions in the worst case",
    spaceComplexity: "O(d)",
    pros: ["Low memory usage", "Finds shallow solutions early like BFS depth ordering"],
    cons: ["Repeats work across limits", "Can be slower than BFS on broad mazes"],
    bestFor: "Memory-constrained search demonstrations and DFS/BFS tradeoff education.",
    interestingFact:
      "IDDFS combines DFS memory behavior with increasing-depth completeness, making it a classic AI search baseline.",
  },
  {
    id: "greedy-best-first",
    name: "Greedy Best-First",
    kind: "Solver",
    summary: "Chooses nodes closest to goal by heuristic only.",
    howItWorks: [
      "Keep frontier ordered by heuristic h(n).",
      "Expand the most goal-looking node.",
      "Add newly discovered neighbors.",
      "Reconstruct once goal is found.",
    ],
    timeComplexity: "Highly input-dependent",
    spaceComplexity: "O(V)",
    pros: ["Very fast in easy layouts", "Small control overhead"],
    cons: ["Not optimal", "Can be misled by local geometry"],
    bestFor: "Quick approximate solving and heuristic demonstrations.",
    interestingFact:
      "Greedy best-first can outperform optimal methods on easy maps but degrade sharply on deceptive ones.",
  },
  {
    id: "bidirectional-bfs",
    name: "Bidirectional BFS",
    kind: "Solver",
    summary: "Runs two BFS waves from start and goal until they meet.",
    howItWorks: [
      "Initialize one queue at start and another at goal.",
      "Alternate expanding the smaller frontier.",
      "Detect when a node is seen by both searches.",
      "Stitch both parent chains into one path.",
    ],
    timeComplexity: "Often far less than single-source BFS",
    spaceComplexity: "O(V)",
    pros: ["Big practical speedups on long corridors", "Still optimal on unweighted graphs"],
    cons: ["More bookkeeping", "Path merge logic is trickier"],
    bestFor: "Large mazes with distant start/goal pairs.",
    interestingFact:
      "Meeting in the middle can reduce explored states exponentially in branching factor terms.",
  },
  {
    id: "dead-end-filling",
    name: "Dead-End Filling",
    kind: "Solver",
    summary: "Prunes leaves iteratively until only solution corridor remains.",
    howItWorks: [
      "Compute each cell degree in the maze graph.",
      "Queue non-start/non-goal dead ends (degree <= 1).",
      "Remove dead ends and update neighbor degrees.",
      "Remaining cells form the final path corridor.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Very different visual style", "No heuristic needed"],
    cons: ["Less intuitive to users expecting search waves", "Best suited to perfect mazes"],
    bestFor: "Teaching maze topology and pruning-based solving.",
    interestingFact:
      "This method solves by elimination, not by explicitly chasing the goal first.",
  },
  {
    id: "lee-wavefront",
    name: "Lee Wavefront",
    kind: "Solver",
    summary: "Distance-wave flood fill from goal, then gradient backtrace from start.",
    howItWorks: [
      "Run BFS-like wavefront from the goal and assign distance labels.",
      "Stop once start is labeled (or all reachable nodes are processed).",
      "Trace from start by repeatedly moving to a neighbor with smaller distance.",
      "Mark traced cells as the final path.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Optimal in unweighted mazes", "Path extraction is simple and deterministic"],
    cons: ["Needs full distance map storage", "Can explore broad regions like BFS"],
    bestFor: "Wave-propagation visualizations and shortest-path extraction via gradients.",
    interestingFact:
      "Lee's algorithm is a classic in PCB routing and grid-based shortest-path problems.",
  },
  {
    id: "wall-follower",
    name: "Wall Follower (Right-Hand)",
    kind: "Solver",
    summary: "Follows one wall consistently to eventually find the goal in simply connected mazes.",
    howItWorks: [
      "Keep a heading and prefer right turn, then straight, then left, then back.",
      "Move through open passages while maintaining wall contact.",
      "Record discovery parents for path reconstruction.",
      "When goal is reached, reconstruct and display the route.",
    ],
    timeComplexity: "Input-dependent, typically O(E) in tree mazes",
    spaceComplexity: "O(V) with parent tracking",
    pros: ["Very intuitive", "Great for demonstrating local decision rules"],
    cons: ["Not generally optimal", "Can fail in non-simply-connected wall topologies"],
    bestFor: "Educational demos of local navigation strategies.",
    interestingFact:
      "In perfect mazes (tree mazes), wall following always reaches the goal because there are no isolated loops.",
  },
  {
    id: "left-wall-follower",
    name: "Wall Follower (Left-Hand)",
    kind: "Solver",
    summary: "Left-hand counterpart of wall following with mirrored turn preference.",
    howItWorks: [
      "Keep one hand on the left wall while moving.",
      "Prefer left turn, then straight, then right, then back.",
      "Track visited/discovered cells and parent links.",
      "Reconstruct path after goal is reached.",
    ],
    timeComplexity: "Input-dependent, typically O(E) in tree mazes",
    spaceComplexity: "O(V) with parent tracking",
    pros: ["Simple local rule", "Useful for comparing handedness behavior"],
    cons: ["Not generally optimal", "Same topology limits as right-hand variant"],
    bestFor: "Educational side-by-side comparison with right-hand wall following.",
    interestingFact:
      "In simply connected mazes, left-hand and right-hand rules both solve, but can produce very different traversal traces.",
  },
  {
    id: "random-mouse",
    name: "Random Mouse",
    kind: "Solver",
    summary: "Chooses random moves at junctions with no directional strategy.",
    howItWorks: [
      "Start at entrance and pick random open move each step.",
      "Record first-discovery parents for optional reconstruction.",
      "Continue wandering until the goal is reached.",
    ],
    timeComplexity: "Highly variable; can be very large",
    spaceComplexity: "O(V) with parent/discovery tracking",
    pros: ["Extremely simple", "Great baseline for comparison"],
    cons: ["Unreliable performance", "No optimality guarantees"],
    bestFor: "Baseline and educational contrast against informed solvers.",
    interestingFact:
      "Random Mouse is often used as the lower-bound benchmark in maze-solver studies.",
  },
  {
    id: "flood-fill",
    name: "Flood Fill (Lee Wavefront)",
    kind: "Solver",
    summary: "Alias of Lee Wavefront under an alternative name.",
    howItWorks: [
      "Delegate solving to Lee Wavefront.",
      "Expand wavefront distances from the goal.",
      "Trace a descending distance gradient back to reconstruct a shortest path.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Familiar flood-fill naming", "Identical correctness to Lee Wavefront"],
    cons: ["Not a separate implementation", "Behavior tracks Lee Wavefront updates"],
    bestFor: "Users expecting flood-fill terminology for wavefront shortest-path solving.",
    interestingFact:
      "In this codebase, flood-fill is a direct alias of lee-wavefront.",
  },
  {
    id: "pledge",
    name: "Pledge Algorithm",
    kind: "Solver",
    summary: "Wall-following with turn accounting to escape loops/islands.",
    howItWorks: [
      "Pick preferred heading.",
      "Move straight when possible; otherwise follow wall.",
      "Track net turn count while wall-following.",
      "Leave wall when heading and turn count reset conditions are met.",
    ],
    timeComplexity: "Input-dependent",
    spaceComplexity: "Low local memory (higher in visualizer for tracing)",
    pros: ["More robust than naive wall following", "Good local-navigation concept"],
    cons: ["Still not shortest-path optimal", "More state than hand-on-wall rule"],
    bestFor: "Comparing local heuristics in non-trivial topologies.",
    interestingFact:
      "Pledge specifically addresses wall-follower failures around detached wall islands.",
  },
  {
    id: "tremaux",
    name: "Tremaux",
    kind: "Solver",
    summary: "Mark-based exploration that avoids repeatedly traversing passages.",
    howItWorks: [
      "Mark edges/passages as they are traversed.",
      "Prefer unmarked exits; backtrack on marked branches.",
      "Avoid over-marked branches unless forced.",
      "Eventually reaches exit if reachable.",
    ],
    timeComplexity: "O(V + E) typical",
    spaceComplexity: "O(V + E) for marks",
    pros: ["Guaranteed for finite mazes", "Human-doable with marks"],
    cons: ["Not shortest-path optimal", "Needs marking memory"],
    bestFor: "Historical human-solvable guaranteed strategy demos.",
    interestingFact:
      "Tremaux's algorithm predates modern graph-search terminology but maps well to DFS ideas.",
  },
  {
    id: "chain",
    name: "Chain (Bidirectional BFS)",
    kind: "Solver",
    summary: "Alias of Bidirectional BFS with legacy naming.",
    howItWorks: [
      "Delegate solving to Bidirectional BFS.",
      "Expand search waves from start and goal.",
      "Stop when both waves meet and stitch the path.",
      "Return the same result as canonical Bidirectional BFS.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Compatibility with chain naming", "Same shortest-path guarantees as Bidirectional BFS"],
    cons: ["Not a distinct algorithm", "No behavior difference from canonical implementation"],
    bestFor: "Users who prefer chain terminology for bidirectional search.",
    interestingFact:
      "In this codebase, chain is a direct alias of bidirectional-bfs.",
  },
  {
    id: "cul-de-sac-filler",
    name: "Cul-de-sac Filler (Dead-End Filling)",
    kind: "Solver",
    summary: "Extends dead-end elimination to prune cul-de-sac style branches.",
    howItWorks: [
      "Identify dead-end-like and cul-de-sac candidates.",
      "Iteratively remove non-solution side branches.",
      "Repeat until only core route structure remains.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Topology-first solving", "Useful structural visualization"],
    cons: ["Less intuitive than path search", "Best with full maze map"],
    bestFor: "Map-analysis style solving workflows.",
    interestingFact:
      "Cul-de-sac pruning can be seen as generalized leaf stripping on maze graphs.",
  },
  {
    id: "blind-alley-sealer",
    name: "Blind Alley Sealer (Dead-End Filling)",
    kind: "Solver",
    summary: "Alias of Dead-End Filling with alternate terminology.",
    howItWorks: [
      "Delegate solving to Dead-End Filling.",
      "Iteratively prune dead-end branches that cannot belong to a solution path.",
      "Leave only the viable corridor structure.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Keeps sealer naming for discoverability", "Matches Dead-End Filling correctness"],
    cons: ["Not a distinct implementation", "Behavior follows Dead-End Filling changes"],
    bestFor: "Users expecting blind-alley sealer naming in elimination-based solvers.",
    interestingFact:
      "In this codebase, blind-alley-sealer is a direct alias of dead-end-filling.",
  },
  {
    id: "blind-alley-filler",
    name: "Blind Alley Filler (Dead-End Filling)",
    kind: "Solver",
    summary: "Alias of Dead-End Filling with alternate terminology.",
    howItWorks: [
      "Delegate solving to Dead-End Filling.",
      "Iteratively remove dead-end branches from the maze graph.",
      "Finish when only viable route corridors remain.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Keeps filler naming for discoverability", "Matches Dead-End Filling correctness"],
    cons: ["Not a distinct implementation", "Behavior follows Dead-End Filling changes"],
    bestFor: "Users expecting blind-alley filler naming in elimination-based solvers.",
    interestingFact:
      "In this codebase, blind-alley-filler is a direct alias of dead-end-filling.",
  },
  {
    id: "collision-solver",
    name: "Collision Solver (Bidirectional BFS)",
    kind: "Solver",
    summary: "Alias of Bidirectional BFS with collision-focused naming.",
    howItWorks: [
      "Delegate solving to Bidirectional BFS.",
      "Expand start and goal frontiers toward each other.",
      "Detect wave collision and stitch parent chains.",
      "Return the same shortest path as canonical Bidirectional BFS.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Collision-oriented naming", "Same shortest-path guarantees as Bidirectional BFS"],
    cons: ["Not a distinct implementation", "No behavior difference from canonical implementation"],
    bestFor: "Users who prefer collision wording for bidirectional search.",
    interestingFact:
      "In this codebase, collision-solver is a direct alias of bidirectional-bfs.",
  },
  {
    id: "shortest-paths-finder",
    name: "Shortest Paths Finder (All)",
    kind: "Solver",
    summary: "Identifies the full set of cells that belong to shortest routes.",
    howItWorks: [
      "Compute distances from start.",
      "Compute distances from goal.",
      "Keep cells where dStart + dGoal equals shortest distance.",
      "Mark resulting shortest-path manifold.",
    ],
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    pros: ["Shows all shortest alternatives", "Great for route multiplicity analysis"],
    cons: ["More data than single-path methods", "Can look dense in open areas"],
    bestFor: "Analyzing alternative optimal routes.",
    interestingFact:
      "A single shortest path is just one sample from this full shortest-path set.",
  },
  {
    id: "shortest-path-finder",
    name: "Shortest Path Finder (BFS)",
    kind: "Solver",
    summary: "Alias of BFS for single shortest-path extraction.",
    howItWorks: [
      "Delegate solving to Breadth-First Search (BFS).",
      "Expand in layers from start over open neighbors.",
      "Reconstruct one shortest path from parent links when goal is reached.",
    ],
    timeComplexity: "O(V + E) on unweighted mazes",
    spaceComplexity: "O(V)",
    pros: ["Clear, search-friendly naming", "Exactly matches BFS shortest-path behavior"],
    cons: ["Not a distinct implementation", "Behavior follows BFS changes"],
    bestFor: "Users who want BFS behavior under a shortest-path-centric label.",
    interestingFact:
      "In this codebase, shortest-path-finder is a direct alias of bfs.",
  },
  {
    id: "q-learning",
    name: "Q-Learning (RL)",
    kind: "Solver",
    summary: "Learns action values through repeated episodes, then follows the learned greedy policy.",
    howItWorks: [
      "Initialize a Q-table for state-action values.",
      "Run episodes with epsilon-greedy exploration.",
      "Update Q-values from rewards and bootstrapped future estimates.",
      "After training, follow highest-valued actions from start to goal.",
    ],
    timeComplexity: "Training-dependent; typically much higher than graph search",
    spaceComplexity: "O(V * A)",
    pros: ["Shows reinforcement-learning behavior", "Adapts through experience instead of hardcoded heuristic"],
    cons: ["Needs many episodes", "No strict shortest-path guarantee without careful tuning"],
    bestFor: "Educational RL comparisons against classical graph-search solvers.",
    interestingFact:
      "Unlike BFS/A*, Q-learning can improve policy quality over repeated runs on the same maze distribution.",
  },
  {
    id: "ant-colony",
    name: "Ant Colony Optimization",
    kind: "Solver",
    summary: "Uses pheromone-guided stochastic exploration where strong routes reinforce over time.",
    howItWorks: [
      "Spawn ants that probabilistically follow local pheromone signals.",
      "Let ants explore, backtrack from dead ends, and record successful paths.",
      "Evaporate pheromones globally and reinforce successful trails.",
      "Extract the strongest discovered route as the final path.",
    ],
    timeComplexity: "Generation/ant-count dependent; typically high",
    spaceComplexity: "O(E) pheromone storage",
    pros: ["Strong emergent behavior visualization", "Good metaheuristic comparison baseline"],
    cons: ["Heuristic/stochastic tuning sensitive", "No strict optimality guarantee"],
    bestFor: "Metaheuristic solver demonstrations and exploration/exploitation tradeoff analysis.",
    interestingFact:
      "ACO was inspired by real ant foraging behavior where pheromone reinforcement biases collective path selection.",
  },
  {
    id: "genetic",
    name: "Genetic Algorithm",
    kind: "Solver",
    summary: "Evolves path-encoding chromosomes and keeps fittest candidates across generations.",
    howItWorks: [
      "Generate an initial random population of move chromosomes.",
      "Simulate each chromosome and score fitness by goal reachability and path quality.",
      "Keep elite candidates and produce offspring with crossover/mutation.",
      "Repeat until convergence or generation budget, then trace best path.",
    ],
    timeComplexity: "O(G * P * L), generations * population * chromosome length",
    spaceComplexity: "O(P * L)",
    pros: ["Handles large noisy search spaces", "Shows exploration vs exploitation behavior"],
    cons: ["No strict optimality guarantee", "Performance depends on hyperparameters"],
    bestFor: "Metaheuristic comparisons and stochastic solver experiments.",
    interestingFact:
      "Genetic solvers trade deterministic guarantees for adaptive search pressure shaped by a fitness function.",
  },
  {
    id: "rrt-star",
    name: "RRT* (Grid Approximation)",
    kind: "Solver",
    summary: "Builds a sampled tree from start and locally rewires for lower-cost parent chains.",
    howItWorks: [
      "Initialize a search tree rooted at start.",
      "Repeatedly sample targets and expand the tree toward promising frontier nodes.",
      "Rewire nearby nodes when the new node yields lower path cost.",
      "Once goal is connected (or budget is exhausted), trace tree path to goal.",
    ],
    timeComplexity: "Sampling-dependent; often near O(K * d) for K expansions",
    spaceComplexity: "O(V) tree state",
    pros: ["Anytime-style sampled exploration", "Natural bridge toward robotics planning concepts"],
    cons: ["Approximation on discrete grids", "Requires iteration budget / fallback policy"],
    bestFor: "Bringing continuous-space planning ideas into grid maze comparisons.",
    interestingFact:
      "RRT* is asymptotically optimal in continuous settings; grid adaptations mimic that behavior with discrete rewiring.",
  },
  {
    id: "wave-function-collapse",
    name: "Wave Function Collapse",
    kind: "Generator",
    summary:
      "Collapses per-cell wall tiles under local compatibility constraints, then carves a connected loopy maze.",
    howItWorks: [
      "Initialize each cell with all 16 possible N/E/S/W wall tiles.",
      "Repeatedly pick the lowest-entropy uncollapsed cell and sample one tile.",
      "Propagate edge-compatibility constraints to neighboring cells.",
      "After collapse, convert open tile edges into carve candidates.",
      "Connect any remaining components and add one extra edge to preserve loops.",
    ],
    timeComplexity: "O(V * T + E α(V)) expected (T = tile options)",
    spaceComplexity: "O(V + E)",
    pros: ["Constraint-driven structure", "Naturally loop-friendly output", "Strong visual progression"],
    cons: ["More bookkeeping than classic tree generators", "Requires propagation logic"],
    bestFor: "Loopy mazes with local texture shaped by tile constraints.",
    interestingFact:
      "WFC popularized entropy + constraint propagation in procedural generation far beyond maze domains.",
  },
  {
    id: "dla",
    name: "Diffusion-Limited Aggregation",
    kind: "Generator",
    summary:
      "Random walkers stick to a growing cluster, carving one joining edge per absorbed particle.",
    howItWorks: [
      "Seed one aggregate cell.",
      "Launch a particle from a random non-aggregate cell.",
      "Random-walk the particle through neighboring cells.",
      "When it touches aggregate territory, carve one connection and absorb it.",
      "Repeat until every cell belongs to the aggregate.",
    ],
    timeComplexity: "Walk-length dependent; typically superlinear",
    spaceComplexity: "O(V)",
    pros: ["Distinct organic branching", "Simple local rule set", "Great stochastic animation"],
    cons: ["Can require many walk steps", "Performance sensitive to kill threshold"],
    bestFor: "Tree mazes with dendritic, frost-like growth patterns.",
    interestingFact:
      "DLA is a classic model for natural branching structures such as dielectric breakdown and mineral growth.",
  },
  {
    id: "hilbert-curve",
    name: "Hilbert Curve",
    kind: "Generator",
    summary:
      "Orders cells by Hilbert-space-filling rank and carves one parent edge per ordered visit.",
    howItWorks: [
      "Compute Hilbert ranks over the enclosing power-of-two square.",
      "Filter ranks to in-bounds cells and sort by rank.",
      "Build a connected parent tree preferring visited neighbors with nearby rank.",
      "Visit cells in rank order and carve each parent-child edge.",
      "Finish when all cells are connected.",
    ],
    timeComplexity: "O(V log V)",
    spaceComplexity: "O(V)",
    pros: ["Fractal-inspired global ordering", "Deterministic output", "Smooth progressive carving"],
    cons: ["Less stochastic variety", "Extra rank-precompute step"],
    bestFor: "Demonstrating space-filling ordering effects in perfect mazes.",
    interestingFact:
      "Hilbert curves preserve locality better than simple raster order, which is useful in indexing and cache layouts.",
  },
  {
    id: "voronoi",
    name: "Voronoi Tessellation",
    kind: "Generator",
    summary:
      "Grows seeded regions, builds a region spanning tree, then carves planned internal and doorway edges.",
    howItWorks: [
      "Scatter region seeds and grow ownership with multi-source BFS rings.",
      "Record growth parents to form a tree inside each region.",
      "Compute region boundary adjacency candidates.",
      "Run a random spanning tree over region graph to pick doorway boundaries.",
      "Carve internal region-tree edges plus selected doorways.",
    ],
    timeComplexity: "O(V + E α(V))",
    spaceComplexity: "O(V + E)",
    pros: ["Clear phase-based animation", "Region-level structure", "Perfect connectivity guarantees"],
    cons: ["More preprocessing than local-walk methods", "Heavily seed-count dependent"],
    bestFor: "Perfect mazes with visible territorial growth behavior.",
    interestingFact:
      "Voronoi partitions are foundational in computational geometry, graphics, and facility-location problems.",
  },
  {
    id: "percolation",
    name: "Percolation",
    kind: "Generator",
    summary:
      "Randomly opens walls with probability p, then stitches components and preserves at least one cycle.",
    howItWorks: [
      "Enumerate and shuffle all internal grid walls.",
      "Percolation phase: carve each wall independently with probability p.",
      "Track connectivity with union-find.",
      "Connect phase: carve remaining walls that merge disconnected components.",
      "If needed, carve one extra unused wall to guarantee loopy topology.",
    ],
    timeComplexity: "O(E α(V))",
    spaceComplexity: "O(V + E)",
    pros: ["Direct loop-density control via probability", "Phase-transition inspired behavior"],
    cons: ["Output character highly parameter-sensitive", "Requires completion pass for guaranteed connectivity"],
    bestFor: "Loopy mazes near critical connectivity thresholds.",
    interestingFact:
      "Percolation theory studies when local random connections suddenly create giant global connectivity.",
  },
  {
    id: "l-system",
    name: "L-System (Lindenmayer)",
    kind: "Generator",
    summary:
      "Expands a grammar string once, turtle-draws corridors, then connects remaining components.",
    howItWorks: [
      "Expand an axiom with production rules up to a capped length.",
      "Interpret symbols as turtle moves, turns, and push/pop branch states.",
      "Carve forward moves while enforcing union-find acyclicity.",
      "Mark traversal overlays as the turtle draws the pattern.",
      "Run a randomized connect pass to absorb remaining isolated components.",
    ],
    timeComplexity: "O(L + E α(V)) (L = expanded string length)",
    spaceComplexity: "O(V + L)",
    pros: ["Grammar-driven visual motifs", "Good branch/trail visualization"],
    cons: ["Rule choice strongly impacts shape", "Can overrun bounds without clamping"],
    bestFor: "Fractal-inspired tree mazes with explicit symbolic generation phases.",
    interestingFact:
      "L-Systems were introduced to model plant growth and later became central to procedural graphics.",
  },
  {
    id: "physarum",
    name: "Physarum (Slime Mold)",
    kind: "Solver",
    summary:
      "Adapts edge conductivities from pressure-driven flow until a dominant route emerges.",
    howItWorks: [
      "Initialize traversable edges with equal conductivity and terminal pressures.",
      "Relax node pressures with conductivity-weighted averaging.",
      "Compute edge flow and update conductivity via growth/decay dynamics.",
      "Repeat until values stabilize.",
      "Extract the path by following strongest conductivities (with fallback pathfinding).",
    ],
    timeComplexity: "O(I * (V + E)) for I flow iterations",
    spaceComplexity: "O(V + E)",
    pros: ["Biologically inspired dynamics", "Rich iterative visualization", "Handles all topologies"],
    cons: ["Iteration-heavy", "Path extraction is heuristic without fallback"],
    bestFor: "Visualizing adaptive network optimization on maze graphs.",
    interestingFact:
      "Real Physarum organisms can approximate shortest paths by reallocating protoplasmic tube thickness.",
  },
  {
    id: "electric-circuit",
    name: "Electric Circuit (Resistor Network)",
    kind: "Solver",
    summary:
      "Solves maze voltages by Laplace relaxation and traces a descending-voltage route to the goal.",
    howItWorks: [
      "Set V(start)=1 and V(goal)=0 with neutral initialization elsewhere.",
      "Run Gauss-Seidel voltage sweeps over non-terminal nodes.",
      "Stop when maximum change is below epsilon or iteration cap is hit.",
      "Interpret voltage gradient as flow potential.",
      "Trace path by steepest local voltage drop (with fallback pathfinding).",
    ],
    timeComplexity: "O(I * (V + E))",
    spaceComplexity: "O(V)",
    pros: ["Smooth gradient visualization", "Deterministic relaxation process"],
    cons: ["Needs many sweeps on larger mazes", "Greedy extraction is heuristic"],
    bestFor: "Potential-field style solver comparisons against discrete graph search.",
    interestingFact:
      "Voltage solutions on resistor networks are tightly linked to random walk probabilities.",
  },
  {
    id: "ida-star",
    name: "IDA* (Iterative Deepening A*)",
    kind: "Solver",
    summary:
      "Runs depth-first f-bound searches with increasing thresholds using an explicit stack.",
    howItWorks: [
      "Initialize threshold with start heuristic to goal.",
      "Perform DFS limited by f=g+h threshold.",
      "Record the minimum exceeded f as next iteration threshold.",
      "Restart with increased bound while reusing lightweight stack state.",
      "Reconstruct path once goal enters the admissible bound.",
    ],
    timeComplexity: "Exponential worst-case; practical depends on heuristic quality",
    spaceComplexity: "O(depth)",
    pros: ["Optimal with admissible heuristic", "Memory-light compared to A*"],
    cons: ["May re-expand nodes across iterations", "Can be slower than A* on broad graphs"],
    bestFor: "Optimal solving when memory pressure matters more than re-expansion cost.",
    interestingFact:
      "IDA* keeps A*-style optimality guarantees while using DFS-like memory.",
  },
  {
    id: "potential-field",
    name: "Artificial Potential Field",
    kind: "Solver",
    summary:
      "Moves greedily along local potential minima with random escape from local minima traps.",
    howItWorks: [
      "Score candidate neighbors by attraction to goal plus repulsion penalties.",
      "Move toward lowest potential neighbor.",
      "Track revisit frequency to detect stagnation.",
      "Inject short random escapes when trapped.",
      "Build and mark discovered path when goal is reached.",
    ],
    timeComplexity: "O(K * d) for K steps and local degree d",
    spaceComplexity: "O(V)",
    pros: ["Fast local decisions", "Simple to animate", "Demonstrates local-minimum behavior"],
    cons: ["Heuristic only", "Can fail without escape strategy"],
    bestFor: "Comparing local-gradient heuristics versus global graph search.",
    interestingFact:
      "Potential-field planning originated in robotics for real-time obstacle avoidance.",
  },
  {
    id: "frontier-explorer",
    name: "Frontier-Based Exploration",
    kind: "Solver",
    summary:
      "Simulates incremental map discovery: explore frontier boundaries, then navigate once goal is known.",
    howItWorks: [
      "Start with partial knowledge around the initial position.",
      "Identify frontier cells bordering unknown space.",
      "Plan to nearest frontier over known traversable graph.",
      "Move one step, reveal neighbors, and update frontier.",
      "When goal becomes known, switch to direct navigation and trace final path.",
    ],
    timeComplexity: "O(K * (V + E)) in repeated BFS replans",
    spaceComplexity: "O(V)",
    pros: ["Strong exploration narrative", "Deterministic and complete on connected mazes"],
    cons: ["Repeated replanning overhead", "More state than simple shortest-path solvers"],
    bestFor: "Fog-of-war style discovery visuals and robotics-inspired exploration behavior.",
    interestingFact:
      "Frontier exploration is widely used in autonomous mapping systems for unknown environments.",
  },
  {
    id: "fringe-search",
    name: "Fringe Search",
    kind: "Solver",
    summary:
      "Processes nodes in threshold layers using now/later lists instead of a priority queue.",
    howItWorks: [
      "Initialize now list with start and threshold from heuristic.",
      "Expand one now-node per step.",
      "Defer nodes with f above threshold into later list.",
      "Relax neighbor costs and parent pointers for admissible nodes.",
      "When now empties, raise threshold to min deferred f and swap lists.",
    ],
    timeComplexity: "Comparable to A* in many grids; worst-case exponential",
    spaceComplexity: "O(V)",
    pros: ["Layered expansion visualization", "Often lower overhead than strict priority queues"],
    cons: ["Implementation complexity vs BFS/A*", "Performance still heuristic-dependent"],
    bestFor: "Comparing threshold-bucket search against A*/IDA* families.",
    interestingFact:
      "Fringe Search was introduced in game pathfinding to reduce priority-queue churn.",
  },
];

export const GENERATOR_DOCS = ALGORITHM_DOCS.filter(
  (algorithm) => algorithm.kind === "Generator",
);

export const SOLVER_DOCS = ALGORITHM_DOCS.filter(
  (algorithm) => algorithm.kind === "Solver",
);
