import type { GeneratorPluginId } from "@/core/plugins/generators";

export interface GeneratorPseudocodeDoc {
  title: string;
  summary: string;
  lines: string[];
}

export const GENERATOR_PSEUDOCODE: Record<
  GeneratorPluginId,
  GeneratorPseudocodeDoc
> = {
  "dfs-backtracker": {
    title: "Recursive Backtracker (DFS)",
    summary: "Depth-first carve with backtracking stack.",
    lines: [
      "if first step: mark start visited and push on stack",
      "if stack is empty: finish",
      "current <- top(stack); unvisited <- neighbors(current)",
      "if unvisited is empty: pop stack and backtrack",
      "pick random unvisited neighbor and carve passage",
      "mark neighbor visited and push neighbor onto stack",
    ],
  },
  prim: {
    title: "Randomized Prim",
    summary: "Grow maze by sampling random frontier cells.",
    lines: [
      "if first step: visit start and seed frontier",
      "if frontier is empty: finish",
      "pick random cell from frontier",
      "connect it to one random visited neighbor",
      "mark cell visited and add its unvisited neighbors to frontier",
      "emit metrics and continue",
    ],
  },
  "prim-true": {
    title: "Prim (True Frontier Edges)",
    summary: "Classic Prim variant that samples frontier edges.",
    lines: [
      "if first step: visit root and enqueue outgoing edges",
      "clear previous current marker",
      "pick random frontier edge until target is unvisited",
      "carve chosen edge and mark target visited/current",
      "enqueue target's outgoing edges to unvisited cells",
      "if no valid frontier edge remains: finish",
    ],
  },
  "prim-simplified": {
    title: "Prim (Simplified)",
    summary: "Frontier-cell Prim with lightweight bookkeeping.",
    lines: [
      "if first step: visit start and seed frontier",
      "if frontier is empty: finish",
      "pick random cell from frontier",
      "connect it to one random visited neighbor",
      "mark cell visited and add its unvisited neighbors to frontier",
      "emit metrics and continue",
    ],
  },
  "prim-modified": {
    title: "Prim (Modified)",
    summary: "Random-active-cell growth (Growing Tree random policy).",
    lines: [
      "if first step: seed active list with start",
      "if active list empty: finish",
      "pick random active cell",
      "if unvisited neighbor exists: carve and append it",
      "else remove active cell from list",
      "emit active-list frontier metrics",
    ],
  },
  "prim-frontier-edges": {
    title: "Prim (Frontier Edges)",
    summary: "Prim variant that samples frontier edges directly.",
    lines: [
      "if first step: visit root and enqueue outgoing edges",
      "clear previous current marker",
      "pick random frontier edge until target is unvisited",
      "carve chosen edge and mark target visited/current",
      "enqueue target's outgoing edges to unvisited cells",
      "if no valid frontier edge remains: finish",
    ],
  },
  kruskal: {
    title: "Randomized Kruskal",
    summary: "Shuffle edges and union disjoint sets.",
    lines: [
      "if all components merged or no edges left: finish",
      "edge <- next shuffled edge",
      "if edge endpoints are in different sets: union and carve",
      "mark touched endpoints as visited overlays",
      "advance cursor and continue",
      "emit remaining frontier edge count",
    ],
  },
  "binary-tree": {
    title: "Binary Tree",
    summary: "Single pass with directional carve bias.",
    lines: [
      "if cursor reached end of grid: finish",
      "cell <- next cell in scan order",
      "candidate directions <- [north, west] when available",
      "if candidates exist: pick one and carve",
      "advance cursor",
      "emit single-cell frontier metrics",
    ],
  },
  sidewinder: {
    title: "Sidewinder",
    summary: "Build row runs and occasionally carve north.",
    lines: [
      "if row cursor is past last row: finish",
      "visit current row cell",
      "decide whether to close current horizontal run",
      "if closing run: carve north from random run member",
      "else: carve east to extend run",
      "advance x/y cursors to next step",
    ],
  },
  "aldous-broder": {
    title: "Aldous-Broder",
    summary: "Random walk; only carve on first visit.",
    lines: [
      "if first step: start random walk at random root",
      "if all cells visited: finish",
      "pick random neighbor of current cell",
      "if neighbor is unvisited: carve and mark visited",
      "move current pointer to picked neighbor",
      "emit walk frontier metrics",
    ],
  },
  "hunt-and-kill": {
    title: "Hunt-and-Kill",
    summary: "Alternate random walk and linear hunt phases.",
    lines: [
      "if first step: mark random start visited",
      "try random walk step to an unvisited neighbor",
      "if walk step exists: carve and move",
      "otherwise scan for unvisited cell adjacent to visited",
      "if scan finds one: connect it and continue walk",
      "if scan finds none: finish",
    ],
  },
  "growing-tree": {
    title: "Growing Tree",
    summary: "Use active list with newest/random selection bias.",
    lines: [
      "if first step: seed active list with start",
      "if active list empty: finish",
      "cell <- select active entry by policy",
      "if unvisited neighbor exists: carve and append neighbor",
      "else: remove cell from active list",
      "emit active-size frontier metrics",
    ],
  },
  "growing-forest": {
    title: "Growing Forest",
    summary: "Grow multiple trees, then connect forest components.",
    lines: [
      "initialize multiple seed trees across the grid",
      "grow each tree into unvisited neighbors",
      "if a tree stalls, remove it from active set",
      "continue until every cell belongs to a tree",
      "connect different trees with boundary edges",
      "finish once one connected forest remains",
    ],
  },
  "recursive-division": {
    title: "Recursive Division",
    summary: "Open field first, then add recursive split walls with gaps.",
    lines: [
      "open all internal walls in the grid",
      "choose region orientation (horizontal or vertical)",
      "place a dividing wall and one random opening",
      "apply wall patches for the divider",
      "recurse into both sub-regions",
      "stop when region cannot be divided further",
    ],
  },
  bsp: {
    title: "Binary Space Partitioning (BSP)",
    summary: "Recursively split regions and connect partitions with one bridge.",
    lines: [
      "if region is a single cell: return",
      "choose vertical or horizontal split by region aspect ratio",
      "recurse on both child partitions",
      "pick one connector crossing the split boundary",
      "append connector edge to merge both partition trees",
      "repeat until every partition collapses to single cells",
    ],
  },
  "blobby-recursive-subdivision": {
    title: "Blobby Recursive Subdivision",
    summary: "Split connected regions into organic blobs, then recurse and bridge.",
    lines: [
      "if region is small: build local spanning tree directly",
      "grow two blob sides from random seeds inside region",
      "if split fails connectivity checks: fall back to local tree",
      "recurse into both blob partitions",
      "carve one boundary connector between blob partitions",
      "finish when all recursive regions are reduced",
    ],
  },
  "fractal-tessellation": {
    title: "Fractal Tessellation",
    summary: "Recursively build quadrants, then connect with 3 bridges.",
    lines: [
      "split region into four recursive quadrants",
      "generate each quadrant subtree",
      "sample cross-boundary connector candidates",
      "shuffle connectors and union quadrant components",
      "carve connectors that join disconnected quadrants",
      "repeat until the whole region is a single tree",
    ],
  },
  "bfs-tree": {
    title: "Randomized BFS Tree",
    summary: "Queue-driven wavefront spanning tree.",
    lines: [
      "if first step: enqueue and visit start",
      "if queue exhausted: finish",
      "cell <- dequeue frontier head",
      "for each unvisited neighbor: carve, visit, enqueue",
      "set next queue head as current",
      "emit queue-based frontier metrics",
    ],
  },
  eller: {
    title: "Eller",
    summary: "Row-wise disjoint-set generation with prebuilt operations.",
    lines: [
      "if no pending operations: finish",
      "take next precomputed carve operation batch",
      "apply carve operations to grid",
      "mark touched cells as visited overlays",
      "advance operation cursor",
      "emit row-progress metrics",
    ],
  },
  houston: {
    title: "Houston (AB + Wilson)",
    summary: "Hybrid: early Aldous-Broder, then Wilson.",
    lines: [
      "if first step: initialize root and AB phase",
      "while AB target not reached: random walk and carve first visits",
      "switch to Wilson mode when AB threshold reached",
      "if Wilson walk empty: start from random unvisited node",
      "Wilson step: hit-tree => carve path, loop => erase, else extend",
      "finish when all cells are in tree",
    ],
  },
  unicursal: {
    title: "Unicursal",
    summary: "Carve one continuous Hamiltonian-style path.",
    lines: [
      "build serpentine order over every grid cell",
      "mark first cell as visited/current",
      "take next cell in order",
      "carve passage between consecutive order cells",
      "advance until final order index",
      "finish with one non-branching route",
    ],
  },
  "cellular-automata": {
    title: "Cellular Automata (Cave-Biased)",
    summary: "Use CA-smoothed mask to bias spanning-tree carving.",
    lines: [
      "generate random cave mask and smooth via CA iterations",
      "seed DFS-style stack with start cell",
      "prefer neighbors with matching cave state",
      "if stuck, backtrack stack",
      "carve selected edge and push next cell",
      "finish when stack is exhausted",
    ],
  },
  vortex: {
    title: "Vortex Maze (Xu/Kaplan-inspired)",
    summary: "DFS-style growth with swirl-biased neighbor scoring around vortex centers.",
    lines: [
      "seed several random vortex centers",
      "start DFS stack from initial cell",
      "score unvisited neighbors by tangent (swirl) direction around nearest center",
      "carve to the highest-scoring neighbor and push to stack",
      "if no unvisited neighbors remain: pop/backtrack",
      "finish when stack becomes empty",
    ],
  },
  "reverse-delete": {
    title: "Reverse-Delete",
    summary: "Start fully open, then add back walls only when safe.",
    lines: [
      "open all internal walls so every adjacent pair is connected",
      "if no candidate edges remain: finish",
      "take next randomized edge candidate",
      "temporarily block that edge and test if endpoints stay connected",
      "if still connected: keep wall (remove edge), else restore edge",
      "continue until all candidates are processed",
    ],
  },
  boruvka: {
    title: "Randomized Boruvka",
    summary: "Per component, pick cheapest outgoing edge and merge in rounds.",
    lines: [
      "if only one component remains: finish",
      "for each component, find minimum-weight outgoing edge",
      "deduplicate chosen edges across components",
      "union and carve every chosen edge that joins different components",
      "update component count and continue to next round",
      "stop when one spanning-tree component remains",
    ],
  },
  "origin-shift": {
    title: "Origin Shift",
    summary: "Shift root of a directed spanning tree to rewire edges.",
    lines: [
      "initialize spanning tree and root origin",
      "choose random neighbor of current root",
      "remove neighbor's old parent edge",
      "connect old root to chosen neighbor",
      "promote neighbor as new root",
      "repeat root shifts until budget is exhausted",
    ],
  },
  wilson: {
    title: "Wilson",
    summary: "Loop-erased random walks into existing tree.",
    lines: [
      "if all nodes are in tree: finish",
      "if walk empty: start from random unvisited node",
      "take random walk step to neighboring node",
      "if walk hits tree: carve whole loop-erased walk",
      "if walk loops: erase cycle suffix",
      "else: extend walk frontier and continue",
    ],
  },
};
