import type { GeneratorPluginId } from "@/core/plugins/generators";

export interface GeneratorPseudocodeDoc {
  title: string;
  summary: string;
  lines: string[];
}

export const GENERATOR_PSEUDOCODE: Record<
  GeneratorPluginId,
  GeneratorPseudocodeDoc
> = {
  "dfs-backtracker": {
    title: "Recursive Backtracker (DFS)",
    summary: "Depth-first carve with backtracking stack.",
    lines: [
      "if first step: mark start visited and push on stack",
      "if stack is empty: finish",
      "current <- top(stack); unvisited <- neighbors(current)",
      "if unvisited is empty: pop stack and backtrack",
      "pick random unvisited neighbor and carve passage",
      "mark neighbor visited and push neighbor onto stack",
    ],
  },
  prim: {
    title: "Randomized Prim",
    summary: "Grow maze by sampling random frontier cells.",
    lines: [
      "if first step: visit start and seed frontier",
      "if frontier is empty: finish",
      "pick random cell from frontier",
      "connect it to one random visited neighbor",
      "mark cell visited and add its unvisited neighbors to frontier",
      "emit metrics and continue",
    ],
  },
  "prim-loopy": {
    title: "Prim (Loopy)",
    summary: "Prim growth plus extra visited-neighbor links controlled by loop density.",
    lines: [
      "if first step: visit start and seed frontier",
      "if frontier is empty: finish",
      "pick random frontier cell and carve one parent edge to visited set",
      "attempt additional visited-neighbor carves based on loop density",
      "mark cell visited and add unvisited neighbors to frontier",
      "repeat until all cells are visited",
    ],
  },
  "prim-true": {
    title: "Prim (True Frontier Edges)",
    summary: "Alias wrapper for Prim (Frontier Edges).",
    lines: [
      "delegate stepper creation to prim-frontier-edges",
      "run canonical frontier-edge Prim step",
      "emit canonical patches/metrics unchanged",
      "repeat until canonical implementation finishes",
      "surface results under prim-true id",
    ],
  },
  "prim-simplified": {
    title: "Prim (Simplified)",
    summary: "Alias wrapper for Randomized Prim.",
    lines: [
      "delegate stepper creation to prim",
      "run canonical frontier-cell Prim step",
      "emit canonical patches/metrics unchanged",
      "repeat until canonical implementation finishes",
      "surface results under prim-simplified id",
    ],
  },
  "prim-modified": {
    title: "Prim (Modified)",
    summary: "Random-active-cell growth (Growing Tree random policy).",
    lines: [
      "if first step: seed active list with start",
      "if active list empty: finish",
      "pick random active cell",
      "if unvisited neighbor exists: carve and append it",
      "else remove active cell from list",
      "emit active-list frontier metrics",
    ],
  },
  "prim-frontier-edges": {
    title: "Prim (Frontier Edges)",
    summary: "Prim variant that samples frontier edges directly.",
    lines: [
      "if first step: visit root and enqueue outgoing edges",
      "clear previous current marker",
      "pick random frontier edge until target is unvisited",
      "carve chosen edge and mark target visited/current",
      "enqueue target's outgoing edges to unvisited cells",
      "if no valid frontier edge remains: finish",
    ],
  },
  kruskal: {
    title: "Randomized Kruskal",
    summary: "Shuffle edges and union disjoint sets.",
    lines: [
      "if all components merged or no edges left: finish",
      "edge <- next shuffled edge",
      "if edge endpoints are in different sets: union and carve",
      "mark touched endpoints as visited overlays",
      "advance cursor and continue",
      "emit remaining frontier edge count",
    ],
  },
  "kruskal-loopy": {
    title: "Kruskal (Loopy)",
    summary: "Build a spanning tree first, then reopen rejected edges by loop budget.",
    lines: [
      "shuffle all edges and run union-find Kruskal tree growth",
      "store rejected (cycle-forming) edges while building the tree",
      "once tree is complete, compute extra-edge budget from loop density",
      "iterate rejected edges in random order and carve up to budget",
      "keep overlays/metrics updated during both phases",
      "finish when budget exhausted or rejected edges end",
    ],
  },
  "binary-tree": {
    title: "Binary Tree",
    summary: "Single pass with directional carve bias.",
    lines: [
      "if cursor reached end of grid: finish",
      "cell <- next cell in scan order",
      "candidate directions <- [north, west] when available",
      "if candidates exist: pick one and carve",
      "advance cursor",
      "emit single-cell frontier metrics",
    ],
  },
  sidewinder: {
    title: "Sidewinder",
    summary: "Build row runs and occasionally carve north.",
    lines: [
      "if row cursor is past last row: finish",
      "visit current row cell",
      "decide whether to close current horizontal run",
      "if closing run: carve north from random run member",
      "else: carve east to extend run",
      "advance x/y cursors to next step",
    ],
  },
  "aldous-broder": {
    title: "Aldous-Broder",
    summary: "Random walk; only carve on first visit.",
    lines: [
      "if first step: start random walk at random root",
      "if all cells visited: finish",
      "pick random neighbor of current cell",
      "if neighbor is unvisited: carve and mark visited",
      "move current pointer to picked neighbor",
      "emit walk frontier metrics",
    ],
  },
  "hunt-and-kill": {
    title: "Hunt-and-Kill",
    summary: "Alternate random walk and linear hunt phases.",
    lines: [
      "if first step: mark random start visited",
      "try random walk step to an unvisited neighbor",
      "if walk step exists: carve and move",
      "otherwise scan for unvisited cell adjacent to visited",
      "if scan finds one: connect it and continue walk",
      "if scan finds none: finish",
    ],
  },
  "growing-tree": {
    title: "Growing Tree",
    summary: "Use active list with newest/random selection bias.",
    lines: [
      "if first step: seed active list with start",
      "if active list empty: finish",
      "cell <- select active entry by policy",
      "if unvisited neighbor exists: carve and append neighbor",
      "else: remove cell from active list",
      "emit active-size frontier metrics",
    ],
  },
  "growing-forest": {
    title: "Growing Forest",
    summary: "Grow multiple trees, then connect forest components.",
    lines: [
      "initialize multiple seed trees across the grid",
      "grow each tree into unvisited neighbors",
      "if a tree stalls, remove it from active set",
      "continue until every cell belongs to a tree",
      "connect different trees with boundary edges",
      "finish once one connected forest remains",
    ],
  },
  "recursive-division": {
    title: "Recursive Division",
    summary: "Open field first, then add recursive split walls with gaps.",
    lines: [
      "open all internal walls in the grid",
      "choose region orientation (horizontal or vertical)",
      "place a dividing wall and one random opening",
      "apply wall patches for the divider",
      "recurse into both sub-regions",
      "stop when region cannot be divided further",
    ],
  },
  "recursive-division-loopy": {
    title: "Recursive Division (Multi-Gap)",
    summary: "Recursive wall-adding with multiple doorway gaps per divider.",
    lines: [
      "open all internal walls in the grid",
      "pick split orientation for current region",
      "select split line and compute gap count from loop density",
      "add divider wall everywhere except selected gaps",
      "recurse into both child regions",
      "finish when regions cannot be split further",
    ],
  },
  bsp: {
    title: "Binary Space Partitioning (BSP)",
    summary: "Recursively split regions and connect partitions with one bridge.",
    lines: [
      "if region is a single cell: return",
      "choose vertical or horizontal split by region aspect ratio",
      "recurse on both child partitions",
      "pick one connector crossing the split boundary",
      "append connector edge to merge both partition trees",
      "repeat until every partition collapses to single cells",
    ],
  },
  "blobby-recursive-subdivision": {
    title: "Blobby Recursive Subdivision",
    summary: "Split connected regions into organic blobs, then recurse and bridge.",
    lines: [
      "if region is small: build local spanning tree directly",
      "grow two blob sides from random seeds inside region",
      "if split fails connectivity checks: fall back to local tree",
      "recurse into both blob partitions",
      "carve one boundary connector between blob partitions",
      "finish when all recursive regions are reduced",
    ],
  },
  "fractal-tessellation": {
    title: "Fractal Tessellation",
    summary: "Recursively build quadrants, then connect with 3 bridges.",
    lines: [
      "split region into four recursive quadrants",
      "generate each quadrant subtree",
      "sample cross-boundary connector candidates",
      "shuffle connectors and union quadrant components",
      "carve connectors that join disconnected quadrants",
      "repeat until the whole region is a single tree",
    ],
  },
  "bfs-tree": {
    title: "Randomized BFS Tree",
    summary: "Queue-driven wavefront spanning tree.",
    lines: [
      "if first step: enqueue and visit start",
      "if queue exhausted: finish",
      "cell <- dequeue frontier head",
      "for each unvisited neighbor: carve, visit, enqueue",
      "set next queue head as current",
      "emit queue-based frontier metrics",
    ],
  },
  eller: {
    title: "Eller",
    summary: "Row-wise disjoint-set generation with prebuilt operations.",
    lines: [
      "if no pending operations: finish",
      "take next precomputed carve operation batch",
      "apply carve operations to grid",
      "mark touched cells as visited overlays",
      "advance operation cursor",
      "emit row-progress metrics",
    ],
  },
  houston: {
    title: "Houston (AB + Wilson)",
    summary: "Hybrid: early Aldous-Broder, then Wilson.",
    lines: [
      "if first step: initialize root and AB phase",
      "while AB target not reached: random walk and carve first visits",
      "switch to Wilson mode when AB threshold reached",
      "if Wilson walk empty: start from random unvisited node",
      "Wilson step: hit-tree => carve path, loop => erase, else extend",
      "finish when all cells are in tree",
    ],
  },
  unicursal: {
    title: "Unicursal",
    summary: "Carve one continuous Hamiltonian-style path.",
    lines: [
      "build serpentine order over every grid cell",
      "mark first cell as visited/current",
      "take next cell in order",
      "carve passage between consecutive order cells",
      "advance until final order index",
      "finish with one non-branching route",
    ],
  },
  "cellular-automata": {
    title: "Cellular Automata (Cave-Biased)",
    summary: "Use CA-smoothed mask to bias spanning-tree carving.",
    lines: [
      "generate random cave mask and smooth via CA iterations",
      "seed DFS-style stack with start cell",
      "prefer neighbors with matching cave state",
      "if stuck, backtrack stack",
      "carve selected edge and push next cell",
      "finish when stack is exhausted",
    ],
  },
  "maze-ca": {
    title: "Maze CA (B3/S12345)",
    summary: "Rule-guided cave mask (Maze rule) steering a deterministic tree carve.",
    lines: [
      "initialize random binary mask",
      "evolve mask with B3/S12345 for fixed iterations",
      "start DFS-like stack from seed cell",
      "prefer neighbors sharing mask state, fallback to any unvisited neighbor",
      "carve and push neighbor, else backtrack when stuck",
      "finish when stack empties",
    ],
  },
  "mazectric-ca": {
    title: "Mazectric CA (B3/S1234)",
    summary: "Mazectric rule variant with straighter-mask guidance and tree carving.",
    lines: [
      "initialize random binary mask",
      "evolve mask with B3/S1234 for fixed iterations",
      "start DFS-like stack from seed cell",
      "prefer neighbors sharing mask state, fallback to any unvisited neighbor",
      "carve and push neighbor, else backtrack when stuck",
      "finish when stack empties",
    ],
  },
  braid: {
    title: "Braid (Dead-End Reduction)",
    summary: "Generate a perfect maze, then open select dead ends to add loops.",
    lines: [
      "generate a base perfect maze (DFS backtracker)",
      "collect and shuffle dead-end cells",
      "take next dead-end candidate",
      "open one closed wall to remove that dead end",
      "repeat until dead-end pass is exhausted",
      "finish with loopy braid topology",
    ],
  },
  "weave-growing-tree": {
    title: "Weave Growing Tree",
    summary: "Grow base tree, then add over/under crossings as tunnel links.",
    lines: [
      "generate a base tree maze with growing-tree policy",
      "scan interior corridor cells in randomized order",
      "find straight-corridor candidates eligible for crossing",
      "add crossing marker and tunnel links between opposite neighbors",
      "stop when crossing target/budget is reached",
      "finish with weave-capable topology",
    ],
  },
  vortex: {
    title: "Vortex Maze (Xu/Kaplan-inspired)",
    summary: "DFS-style growth with swirl-biased neighbor scoring around vortex centers.",
    lines: [
      "seed several random vortex centers",
      "start DFS stack from initial cell",
      "score unvisited neighbors by tangent (swirl) direction around nearest center",
      "carve to the highest-scoring neighbor and push to stack",
      "if no unvisited neighbors remain: pop/backtrack",
      "finish when stack becomes empty",
    ],
  },
  "reverse-delete": {
    title: "Reverse-Delete",
    summary: "Start fully open, then add back walls only when safe.",
    lines: [
      "open all internal walls so every adjacent pair is connected",
      "if no candidate edges remain: finish",
      "take next randomized edge candidate",
      "temporarily block that edge and test if endpoints stay connected",
      "if still connected: keep wall (remove edge), else restore edge",
      "continue until all candidates are processed",
    ],
  },
  boruvka: {
    title: "Randomized Boruvka",
    summary: "Per component, pick cheapest outgoing edge and merge in rounds.",
    lines: [
      "if only one component remains: finish",
      "for each component, find minimum-weight outgoing edge",
      "deduplicate chosen edges across components",
      "union and carve every chosen edge that joins different components",
      "update component count and continue to next round",
      "stop when one spanning-tree component remains",
    ],
  },
  "resonant-phase-lock": {
    title: "Resonant Phase-Lock",
    summary: "Frontier growth guided by a dynamic interference-phase resonance score.",
    lines: [
      "initialize interference field, seed visited root, and add frontier",
      "if frontier is empty: finish",
      "pick frontier cell with highest (resonance + parent alignment) score",
      "carve to best visited parent and assign blended phase to new cell",
      "pulse nearby frontier resonance and add newly exposed frontier cells",
      "repeat until every cell is visited",
    ],
  },
  "origin-shift": {
    title: "Origin Shift",
    summary: "Shift root of a directed spanning tree to rewire edges.",
    lines: [
      "initialize spanning tree and root origin",
      "choose random neighbor of current root",
      "remove neighbor's old parent edge",
      "connect old root to chosen neighbor",
      "promote neighbor as new root",
      "repeat root shifts until budget is exhausted",
    ],
  },
  wilson: {
    title: "Wilson",
    summary: "Loop-erased random walks into existing tree.",
    lines: [
      "if all nodes are in tree: finish",
      "if walk empty: start from random unvisited node",
      "take random walk step to neighboring node",
      "if walk hits tree: carve whole loop-erased walk",
      "if walk loops: erase cycle suffix",
      "else: extend walk frontier and continue",
    ],
  },
  erosion: {
    title: "Erosion (Hydraulic)",
    summary: "Simulate water flowing downhill across terrain; erosion feedback creates dendritic river-network branching.",
    lines: [
      "generate smooth heightmap from random control points",
      "seed outlet (lowest cell) as tree root",
      "pop lowest-height frontier cell (water flows downhill)",
      "connect to tree-neighbor with steepest descent",
      "erode: lower unvisited neighbor heights (feedback loop)",
      "finish when all cells are in tree",
    ],
  },
  "quantum-seismogenesis": {
    title: "Quantum Seismogenesis",
    summary: "Build stress in the grid until a rapid fracture connects disjoint sets.",
    lines: [
      "if all components merged: finish",
      "process active fracture tips and propagate to highest stress neighbors",
      "if a fracture hits a different component: union and carve path",
      "if no active fractures: add random stress to cells",
      "if cell stress reaches critical threshold: ignite new fracture",
      "wait for next step",
    ],
  },
  "mycelial-anastomosis": {
    title: "Mycelial Anastomosis",
    summary: "Concurrent organic growth from multiple spores, merging on contact.",
    lines: [
      "if all components merged: clear frontiers and finish",
      "if no active hyphae: spawn a new hypha in unvisited cell",
      "pick a random active hypha tip and shuffle its valid neighbors",
      "if neighbor unvisited: grow into it and branch occasionally",
      "if neighbor visited by different network: merge and terminate tip",
      "wait for next step",
    ],
  },
  "counterfactual-cycle-annealing": {
    title: "Counterfactual Cycle Annealing",
    summary:
      "Seed a tree, then repeatedly swap one added chord and one removed cycle edge using annealed counterfactual scoring.",
    lines: [
      "build a seed spanning tree with randomized DFS-style growth",
      "pick a high-stress cell and propose one currently closed edge",
      "find the unique tree path between proposed edge endpoints",
      "score each removable edge on that path using local counterfactual energy",
      "accept or reject the best swap with simulated annealing temperature",
      "stop after swap budget; preserve connected acyclic tree topology",
    ],
  },
  "sandpile-avalanche": {
    title: "Sandpile Avalanche",
    summary: "Self-organized criticality: drop sand, topple at threshold, carve passages during avalanche cascades.",
    lines: [
      "pre-seed each cell with 1–3 sand grains (near criticality)",
      "drop one grain on a random cell",
      "while any cell has sand >= 4: topple (−4 to self, +1 to each neighbor)",
      "if a topple crosses a component boundary: carve passage and merge",
      "if carve drought exceeds threshold: bias drops toward boundary cells",
      "repeat until all cells are in one component",
    ],
  },
  "reaction-diffusion": {
    title: "Reaction-Diffusion (Turing)",
    summary: "Simulate Gray-Scott reaction-diffusion kinetics, thresholding concentration to carve organic passages.",
    lines: [
      "initialize continuous concentrations of chemicals A and B with seed noise",
      "fast-forward diffusion and reaction using the Gray-Scott laplacian",
      "when the pattern stabilizes, threshold the continuous A field into a binary passage mask",
      "if passages share a wall, carve them",
      "run Kruskal's random bridge-builder on separated stripes to ensure one component",
      "finish once the generated Turing structures are fully spanning",
    ],
  },
  "ant-colony": {
    title: "Ant Colony Excavation",
    summary: "Simulate pheromone-leaving ant agents digging a spanning tree.",
    lines: [
      "if all cells are connected into one component: finish",
      "update each ant's age; respawn old ants at random disconnected locations",
      "ants pick neighboring cells weighted strongly by existing pheromone trails",
      "if neighbor belongs to a different component: tunnel and connect them",
      "leave new pheromone where the ant steps",
      "evaporate all pheromone slightly and repeat for next step",
    ],
  },
  "ising-model": {
    title: "Magnetic Spin Crystallization",
    summary: "Simulate Ising spins via Metropolis-Hastings, crystallizing spin networks into passage weights.",
    lines: [
      "if all cells are connected: finish",
      "simulate ferromagnetism: attempt random cell spin flips",
      "evaluate energy delta favoring sequences with 2 matching neighbors",
      "accept or reject flips via simulated annealing probabilities",
      "when cooled, assign edge weights favoring positive-spin matching connections",
      "run Kruskal's algorithm influenced by the spin grid weights",
    ],
  },
  "wave-function-collapse": {
    title: "Wave Function Collapse",
    summary: "Entropy-guided tile collapse with local constraint propagation.",
    lines: [
      "initialize each cell with all 16 wall-config tiles as possibilities",
      "pick the uncollapsed cell with minimum entropy and collapse one tile by rng",
      "propagate compatibility constraints through neighbors until stable",
      "repeat collapse/propagate until all cells become fixed",
      "translate tile openings into candidate carved edges",
      "connect components and add one extra edge to preserve loopy topology",
    ],
  },
  dla: {
    title: "Diffusion-Limited Aggregation",
    summary: "Random walkers stick to a growing aggregate and carve one joining edge.",
    lines: [
      "seed one random aggregate cell",
      "launch a particle from a random non-aggregate cell",
      "perform random walk micro-steps",
      "if particle touches aggregate, carve one edge and absorb it",
      "if particle exceeds age limit, discard and relaunch",
      "finish when aggregate covers all cells",
    ],
  },
  "hilbert-curve": {
    title: "Hilbert Curve",
    summary: "Order cells by Hilbert rank and carve one parent edge per step.",
    lines: [
      "compute enclosing power-of-two Hilbert ranks with iterative d2xy",
      "sort all in-bounds cells by rank",
      "build a connected parent tree preferring visited neighbors with closest rank",
      "emit root as first visited node",
      "each step carve parent-child edge for next ranked node",
      "continue until every cell is visited exactly once",
    ],
  },
  voronoi: {
    title: "Voronoi Tessellation",
    summary: "Grow seed regions, connect regions as a tree, then carve planned edges.",
    lines: [
      "pick K random seeds and assign one region per seed",
      "expand regions by multi-source BFS rings",
      "record per-cell growth parent to form region-internal trees",
      "build boundary adjacency between different regions",
      "run random spanning tree over regions and pick doorway edges",
      "carve all planned internal + doorway edges",
    ],
  },
  percolation: {
    title: "Percolation",
    summary: "Randomly open bonds, then stitch components and force at least one loop.",
    lines: [
      "enumerate and shuffle all internal walls",
      "percolation phase: carve each edge with probability p",
      "track component merges with union-find",
      "connect phase: carve remaining edges that join different components",
      "if output is still a tree, carve one extra unused edge",
      "finish as connected loopy maze",
    ],
  },
  "l-system": {
    title: "L-System (Lindenmayer)",
    summary: "Expand grammar once, turtle-draw corridors, then connect leftovers.",
    lines: [
      "expand axiom F with production rules up to capped length",
      "interpret symbols: F move/carve, +/- turn, [] push/pop turtle state",
      "only carve when union-find says edge joins different components",
      "mark turtle trail and visited cells during drawing",
      "run randomized union-find connect pass over remaining edges",
      "finish when all cells are in one connected component",
    ],
  },
};
